/*
 * curriculum.js
 * 物理實驗室 — 課程結構資料
 * 依教育部 108 課綱「自然科學領域—物理」規劃，涵蓋必修物理與選修物理（加深加廣）。
 * 12 個學習模組 · 69 個實驗主題，每一個都附即時互動模擬。
 * 公式以 LaTeX 撰寫（String.raw 保留反斜線），由 MathJax 排版。
 * 本檔為原創教材資料，物理模型為教學簡化版，數值以概念示範為主。
 */
(function () {
  "use strict";
  const R = String.raw;
  const I = true; // 所有實驗皆為互動模擬

  const MODULES = [
    {
      no: "一", id: "kinematics", title: "運動學", track: "必修 · 選修力學一", color: "#4dd0e1",
      intro: "描述物體如何運動——位置、位移、速度與加速度，等加速度運動、自由落體、拋體運動與相對運動。",
      experiments: [
        { id: "uniform-accel", title: "等加速度直線運動", interactive: I,
          concept: "加速度固定時，速度隨時間線性變化，位移為 v–t 圖下的面積。調整初速與加速度，觀察 x–t 與 v–t 圖如何改變。",
          formula: R`\( v = v_0 + at,\quad s = v_0 t + \tfrac{1}{2}at^2,\quad v^2 = v_0^2 + 2as \)`,
          points: ["v–t 圖斜率為加速度", "v–t 圖面積為位移", "三大等加速度運動公式", "a 為負代表減速"] },
        { id: "freefall", title: "自由落體", interactive: I,
          concept: "只受重力作用的落體是等加速度運動的特例（a = g）；落地時間與速率只與高度和 g 有關，與質量無關。",
          formula: R`\( v = gt,\quad h = \tfrac{1}{2}gt^2,\quad v = \sqrt{2gh},\quad g \approx 9.8\ \mathrm{m/s^2} \)`,
          points: ["初速為零由靜止落下", "落地速率與 √高度 成正比", "與物體質量無關", "v–t 圖為過原點直線"] },
        { id: "projectile", title: "拋體運動", interactive: I,
          concept: "拋體同時進行水平等速度與鉛直等加速度運動；兩方向彼此獨立。改變發射角與初速觀察射程與最大高度。",
          formula: R`\( x = v_0\cos\theta\,t,\quad y = v_0\sin\theta\,t - \tfrac{1}{2}gt^2,\quad R = \dfrac{v_0^2\sin 2\theta}{g} \)`,
          points: ["水平方向速度分量固定", "鉛直方向為自由落體", "45° 在平地射程最遠", "軌跡為拋物線"] },
        { id: "relative-motion", title: "相對運動與參考系", interactive: I,
          concept: "速度會隨觀察者所在參考系而不同，可用向量相加求相對速度。以過河船為例，調整船速與水流觀察合速度與漂移。",
          formula: R`\( \vec{v}_{A/B} = \vec{v}_{A} - \vec{v}_{B},\quad v = \sqrt{v_x^2 + v_y^2} \)`,
          points: ["選定參考系是描述運動的前提", "相對速度為向量差", "過河最短時間 vs 最短路徑", "常見於船渡河、飛機遇風"] },
        { id: "vt-graph", title: "運動圖形分析", interactive: I,
          concept: "同一段運動可用 x–t、v–t、a–t 三種圖形描述；斜率與面積把三者連結起來。拖動控制點即時比較三圖。",
          formula: R`\( v = \dfrac{dx}{dt},\quad a = \dfrac{dv}{dt},\quad \Delta x = \int v\,dt \)`,
          points: ["x–t 斜率為速度", "v–t 斜率為加速度", "v–t 面積為位移", "圖形是運動的語言"] }
      ]
    },
    {
      no: "二", id: "newton", title: "牛頓運動定律與力", track: "必修 · 選修力學一", color: "#ff8a65",
      intro: "力如何改變運動狀態——慣性、F = ma、作用與反作用，以及斜面、摩擦、張力與連接體問題。",
      experiments: [
        { id: "inertia", title: "慣性與牛頓第一運動定律", interactive: I,
          concept: "不受外力（或合力為零）的物體維持原有運動狀態。改變摩擦係數，觀察滑塊因慣性繼續前進的距離。",
          formula: R`\( \sum \vec{F} = 0 \;\Rightarrow\; \vec{v} = \text{定值} \)`,
          points: ["物體傾向保持原狀態", "慣性大小由質量決定", "無摩擦則永遠等速前進", "安全帶與慣性"] },
        { id: "newton2", title: "牛頓第二運動定律 F = ma", interactive: I,
          concept: "物體加速度與合力成正比、與質量成反比，方向與合力相同。施加不同的力與質量，觀察加速度變化。",
          formula: R`\( \sum \vec{F} = m\vec{a},\quad a = \dfrac{F}{m} \)`,
          points: ["合力決定加速度", "質量是慣性的量度", "1 N = 1 kg·m/s²", "同力下質量越大越難加速"] },
        { id: "incline", title: "斜面上的物體受力", interactive: I,
          concept: "斜面上的物體受重力、正向力與摩擦力；將重力沿斜面與垂直斜面分解可求加速度。調整角度與摩擦觀察下滑或靜止。",
          formula: R`\( mg\sin\theta - \mu mg\cos\theta = ma,\quad N = mg\cos\theta \)`,
          points: ["重力分解為 mg sinθ 與 mg cosθ", "靜摩擦最大值 = μₛN", "θ 增大下滑加速度增大", "μ > tanθ 時靜止"] },
        { id: "friction", title: "靜摩擦與動摩擦", interactive: I,
          concept: "接觸面阻礙相對運動的力，靜摩擦可變且有最大值，物體開始滑動後轉為近似定值的動摩擦。拉動拉力觀察臨界點。",
          formula: R`\( f_s \le \mu_s N,\quad f_k = \mu_k N,\quad \mu_s > \mu_k \)`,
          points: ["靜摩擦隨外力增大", "超過最大靜摩擦即滑動", "動摩擦近似定值", "μ 與接觸面性質有關"] },
        { id: "atwood", title: "連接體與張力（阿特午機）", interactive: I,
          concept: "以繩連接的兩物體可視為整體求加速度，再對個別物體求繩張力。改變兩端質量觀察系統的運動與張力。",
          formula: R`\( a = \dfrac{(m_1-m_2)g}{m_1+m_2},\quad T = \dfrac{2m_1 m_2 g}{m_1+m_2} \)`,
          points: ["整體法求加速度", "隔離法求繩張力", "理想繩張力處處相等", "質量相等時系統靜止"] },
        { id: "newton3", title: "牛頓第三運動定律", interactive: I,
          concept: "作用力與反作用力大小相等、方向相反，且作用在不同物體上，故不會抵消。以兩人推牆或火箭示範作用—反作用對。",
          formula: R`\( \vec{F}_{AB} = -\vec{F}_{BA} \)`,
          points: ["成對出現", "作用在不同物體不抵消", "與物體質量無關", "反衝與推進的基礎"] }
      ]
    },
    {
      no: "三", id: "momentum", title: "動量與碰撞", track: "選修力學一", color: "#ba68c8",
      intro: "動量、衝量與碰撞——沒有外力時系統總動量守恆，彈性碰撞另滿足動能守恆。",
      experiments: [
        { id: "collision", title: "一維碰撞", interactive: I,
          concept: "兩物體碰撞時系統總動量守恆；彈性碰撞另滿足動能守恆，非彈性碰撞則有動能損失。調整回復係數觀察碰後速度。",
          formula: R`\( m_1u_1 + m_2u_2 = m_1v_1 + m_2v_2,\quad e = \dfrac{v_2-v_1}{u_1-u_2} \)`,
          points: ["動量恆守恆", "彈性碰撞動能不變", "完全非彈性碰後合為一體", "回復係數 e 介於 0 與 1"] },
        { id: "momentum-cons", title: "動量守恆定律", interactive: I,
          concept: "系統不受外力（或外力和為零）時，總動量保持不變，源自牛頓第三定律。觀察碰撞前後總動量向量恆定。",
          formula: R`\( \sum \vec{p} = \sum m\vec{v} = \text{定值} \)`,
          points: ["源自牛頓第三定律", "向量式守恆", "適用碰撞、爆炸、反衝", "外力衝量改變總動量"] },
        { id: "impulse", title: "衝量與動量定理", interactive: I,
          concept: "力對時間的累積（衝量）等於動量的變化量。改變作用時間，觀察相同動量變化下所需的力如何不同。",
          formula: R`\( \vec{J} = \int \vec{F}\,dt = \Delta \vec{p},\quad F_{avg} = \dfrac{\Delta p}{\Delta t} \)`,
          points: ["衝量為力–時間圖面積", "延長作用時間可減小衝擊力", "安全氣囊與緩衝墊原理", "衝量與動量同單位"] },
        { id: "collision2d", title: "二維碰撞", interactive: I,
          concept: "平面碰撞時 x、y 兩方向動量各自守恆。調整入射角與瞄準參數，觀察兩球碰後分飛的方向。",
          formula: R`\( \sum p_x = \text{定值},\quad \sum p_y = \text{定值} \)`,
          points: ["各分量獨立守恆", "等質量彈性碰撞後夾 90°", "撞球檯上的應用", "瞄準參數決定散射角"] },
        { id: "recoil", title: "反衝與爆炸", interactive: I,
          concept: "靜止系統分裂時各部分動量大小相等、方向相反，總動量仍為零。示範槍枝後座與火箭推進。",
          formula: R`\( 0 = m_1v_1 + m_2v_2,\quad v_1 = -\dfrac{m_2}{m_1}v_2 \)`,
          points: ["火箭推進原理", "槍枝後座力", "總動量守恆為零", "質量小者速度大"] }
      ]
    },
    {
      no: "四", id: "energy", title: "功與能量", track: "必修 · 選修力學一", color: "#81c784",
      intro: "功、動能與位能——力學能守恆，功率、功能定理與保守力的概念。",
      experiments: [
        { id: "work-power", title: "功與功率", interactive: I,
          concept: "力沿位移方向所做的功，以及做功的快慢（功率）。改變施力大小與方向角，觀察有效作功與功率。",
          formula: R`\( W = Fs\cos\theta,\quad P = \dfrac{W}{t} = Fv \)`,
          points: ["功是純量", "垂直方向的力不做功", "1 W = 1 J/s", "功率為作功速率"] },
        { id: "work-energy", title: "功能定理", interactive: I,
          concept: "合力對物體所做的淨功等於其動能的變化。對滑塊施力一段距離，觀察速度與動能如何隨淨功增加。",
          formula: R`\( W_{net} = \Delta K = \tfrac{1}{2}mv^2 - \tfrac{1}{2}mv_0^2 \)`,
          points: ["淨功改變動能", "連結力與運動", "適用變力問題", "負功使物體減速"] },
        { id: "energy-track", title: "軌道上的力學能守恆", interactive: I,
          concept: "無摩擦軌道上動能與重力位能互相轉換，但力學能總和不變；加入摩擦則力學能逐漸轉為熱。調整起始高度與摩擦。",
          formula: R`\( E = K + U = \tfrac{1}{2}mv^2 + mgh = \text{定值} \)`,
          points: ["最高點位能最大動能最小", "最低點動能最大", "有摩擦力學能轉熱能", "能量守恆是核心概念"] },
        { id: "potential", title: "重力位能與彈性位能", interactive: I,
          concept: "物體因位置或形變而儲存的能量。壓縮彈簧再釋放，觀察彈性位能轉為動能再轉為重力位能。",
          formula: R`\( U_g = mgh,\quad U_s = \tfrac{1}{2}kx^2 \)`,
          points: ["位能與參考點有關", "彈性位能與形變平方成正比", "皆為保守力位能", "位能可完全轉為動能"] },
        { id: "conservative", title: "保守力與非保守力", interactive: I,
          concept: "保守力做功與路徑無關；非保守力（如摩擦）會消耗力學能。比較同一物體走不同路徑時力學能的變化。",
          formula: R`\( W_{\text{保守}} = -\Delta U,\quad \oint \vec{F}_{\text{保守}}\cdot d\vec{r} = 0 \)`,
          points: ["重力、彈力為保守力", "摩擦力為非保守力", "保守力做功只看起訖點", "非保守力使力學能不守恆"] }
      ]
    },
    {
      no: "五", id: "gravity", title: "圓周運動與萬有引力", track: "必修 · 選修力學一", color: "#ffd54f",
      intro: "等速圓周運動與向心力，牛頓萬有引力、人造衛星、克卜勒行星運動定律與角動量守恆。",
      experiments: [
        { id: "circular", title: "等速圓周運動", interactive: I,
          concept: "沿圓周等速率運動時，加速度指向圓心；速率不變但速度方向持續改變。調整半徑與角速度觀察速度與加速度向量。",
          formula: R`\( a_c = \dfrac{v^2}{r} = \omega^2 r,\quad v = \omega r,\quad T = \dfrac{2\pi r}{v} \)`,
          points: ["速率不變速度方向改變", "向心加速度指向圓心", "週期與角速度成反比", "速度恆與半徑垂直"] },
        { id: "centripetal", title: "向心力", interactive: I,
          concept: "維持圓周運動所需、指向圓心的合力。以繩繫小球旋轉為例，觀察張力如何隨速率與半徑改變，並示範脫離時的切線飛出。",
          formula: R`\( F_c = \dfrac{mv^2}{r} = m\omega^2 r \)`,
          points: ["向心力指向圓心", "由張力/重力/摩擦等提供", "斷繩後沿切線飛出", "與 v² 成正比"] },
        { id: "gravitation", title: "萬有引力定律", interactive: I,
          concept: "任兩質點相互吸引，力與質量乘積成正比、與距離平方成反比。改變距離觀察引力的平方反比變化。",
          formula: R`\( F = G\dfrac{m_1 m_2}{r^2},\quad g = \dfrac{GM}{R^2},\quad G = 6.67\times10^{-11} \)`,
          points: ["平方反比定律", "解釋重力與天體運動", "距離加倍引力變 1/4", "g 隨高度減小"] },
        { id: "orbit", title: "行星軌道與克卜勒定律", interactive: I,
          concept: "行星在萬有引力作用下沿橢圓軌道繞恆星運行，掃過的面積速率固定。調整初速觀察圓、橢圓、拋物線軌道的轉變。",
          formula: R`\( F = \dfrac{GMm}{r^2},\quad T^2 \propto a^3,\quad \dfrac{dA}{dt}=\text{定值} \)`,
          points: ["軌道為橢圓恆星在焦點", "近日點速度較快（等面積律）", "週期平方與半長軸立方成正比", "向心力由萬有引力提供"] },
        { id: "satellite", title: "人造衛星與脫離速度", interactive: I,
          concept: "衛星以萬有引力為向心力繞行；達到脫離速度即可擺脫引力束縛。調整發射速率觀察繞行、脫離或墜落。",
          formula: R`\( v_{\text{軌道}} = \sqrt{\dfrac{GM}{r}},\quad v_{\text{脫離}} = \sqrt{\dfrac{2GM}{R}} \)`,
          points: ["近地軌道速率約 7.9 km/s", "脫離速率約 11.2 km/s", "同步衛星週期 24 小時", "軌道速率隨半徑減小"] },
        { id: "angular-momentum", title: "角動量守恆", interactive: I,
          concept: "無外力矩時系統角動量保持不變，解釋行星等面積律與溜冰收手加速。改變半徑觀察轉速的補償變化。",
          formula: R`\( L = mvr = I\omega = \text{定值} \)`,
          points: ["等面積律的本質", "半徑縮小則轉速增快", "花式溜冰收手加速", "無外力矩才守恆"] }
      ]
    },
    {
      no: "六", id: "shm", title: "簡諧運動", track: "選修力學一", color: "#4fc3f7",
      intro: "彈簧振子與單擺——回復力與位移成正比的週期性運動，位移、速度、加速度與能量的變化。",
      experiments: [
        { id: "spring", title: "彈簧振子", interactive: I,
          concept: "彈簧回復力與位移成正比且方向相反，使物體作簡諧運動；動能與彈性位能週期性互換。調整質量與勁度觀察週期。",
          formula: R`\( F = -kx,\quad T = 2\pi\sqrt{\dfrac{m}{k}},\quad x = A\cos(\omega t) \)`,
          points: ["回復力 F = −kx", "週期與振幅無關", "平衡點速度最大", "端點加速度最大"] },
        { id: "pendulum", title: "單擺", interactive: I,
          concept: "小角度擺動時單擺近似簡諧運動，週期只與擺長和重力有關，與質量、振幅無關。調整擺長觀察週期並可測 g。",
          formula: R`\( T = 2\pi\sqrt{\dfrac{L}{g}},\quad \theta = \theta_0\cos(\omega t) \)`,
          points: ["需小角度近似（< 10°）", "週期與擺錘質量無關", "擺長越長週期越長", "可用來測量 g"] },
        { id: "shm-graph", title: "簡諧運動的位移–時間關係", interactive: I,
          concept: "位移隨時間呈正弦變化，速度與加速度亦為正弦函數且彼此有相位差。調整振幅、週期與相位觀察三條曲線。",
          formula: R`\( x = A\cos(\omega t + \varphi),\ v = -A\omega\sin(\omega t),\ a = -\omega^2 x \)`,
          points: ["ω = 2π/T 為角頻率", "加速度與位移成正比反向", "速度超前位移 90°", "相位差描述超前落後"] },
        { id: "shm-energy", title: "簡諧運動的能量", interactive: I,
          concept: "簡諧運動中總力學能守恆，動能與位能隨位置交替變化。觀察動能與位能沿位移的分配與總和恆定。",
          formula: R`\( E = \tfrac{1}{2}kA^2,\quad K = \tfrac{1}{2}k(A^2 - x^2) \)`,
          points: ["總能與振幅平方成正比", "平衡點動能最大", "端點位能最大", "能量在動能位能間流動"] },
        { id: "resonance", title: "共振", interactive: I,
          concept: "外力頻率接近系統自然頻率時，振幅急遽增大。掃動驅動頻率，觀察振幅在共振點附近的尖峰與阻尼影響。",
          formula: R`\( f_{\text{驅動}} \approx f_0,\quad A_{max}\propto \dfrac{1}{\text{阻尼}} \)`,
          points: ["能量最有效傳遞", "橋樑共振破壞", "樂器與收音機選台", "阻尼越小尖峰越高"] }
      ]
    },
    {
      no: "七", id: "thermal", title: "流體與熱學", track: "選修力學二與熱學", color: "#e57373",
      intro: "浮力與白努利原理、理想氣體與分子動能論、氣體定律，以及熱力學基本定律。",
      experiments: [
        { id: "buoyancy", title: "浮力與阿基米德原理", interactive: I,
          concept: "浸在流體中的物體受向上浮力，大小等於排開流體的重量；物體密度小於流體則浮起。調整密度觀察沉浮與沒入比例。",
          formula: R`\( F_b = \rho_{\text{流}}\,g\,V_{\text{排}},\quad \dfrac{V_{\text{沒}}}{V} = \dfrac{\rho_{\text{物}}}{\rho_{\text{流}}} \)`,
          points: ["浮力等於排開流體重量", "沉浮取決於密度比較", "沒入比例 = 密度比", "潛水艇與熱氣球原理"] },
        { id: "bernoulli", title: "白努利原理", interactive: I,
          concept: "理想流體流速快處壓力小，源自能量守恆。改變管徑，觀察流速與壓力此消彼長，並示範機翼升力。",
          formula: R`\( P + \tfrac{1}{2}\rho v^2 + \rho gh = \text{定值} \)`,
          points: ["流速快壓力低", "連續方程 A₁v₁ = A₂v₂", "機翼升力來源", "文氏管與噴霧器"] },
        { id: "gas", title: "理想氣體與分子動能論", interactive: I,
          concept: "氣體由大量隨機運動的分子組成；溫度反映分子平均動能，分子撞擊器壁形成壓力。調整溫度與體積觀察分子運動與壓力。",
          formula: R`\( PV = nRT,\quad \tfrac{1}{2}m\langle v^2\rangle = \tfrac{3}{2}kT \)`,
          points: ["溫度越高分子平均速率越大", "壓力來自分子碰撞", "PV = nRT 理想氣體方程", "體積縮小壓力增大"] },
        { id: "gas-laws", title: "氣體定律（波以耳/查理）", interactive: I,
          concept: "理想氣體壓力、體積、溫度互相牽動：定溫時 PV 定值，定壓時 V∝T。切換過程，觀察 P–V 圖上的變化。",
          formula: R`\( P_1V_1 = P_2V_2,\quad \dfrac{V_1}{T_1} = \dfrac{V_2}{T_2},\quad \dfrac{P_1}{T_1}=\dfrac{P_2}{T_2} \)`,
          points: ["波以耳定律 PV 定值", "查理定律 V∝T", "給呂薩克 P∝T", "P–V 圖描述熱力過程"] },
        { id: "heat", title: "熱平衡與比熱", interactive: I,
          concept: "兩物體接觸時熱由高溫流向低溫直到達成熱平衡；比熱越大溫度變化越慢。混合冷熱水，觀察終溫由熱量守恆決定。",
          formula: R`\( Q = mc\Delta T,\quad m_1c_1\Delta T_1 = m_2c_2\Delta T_2 \)`,
          points: ["熱量由高溫流向低溫", "比熱是升溫難易的量度", "熱平衡時溫度相同", "熱量守恆（無散失）"] },
        { id: "thermo1", title: "熱力學第一定律", interactive: I,
          concept: "系統內能變化等於吸收的熱量減去對外所做的功，是能量守恆的表現。切換等溫、等壓、絕熱過程觀察能量帳。",
          formula: R`\( \Delta U = Q - W,\quad W = \int P\,dV \)`,
          points: ["內能為狀態函數", "熱與功皆為能量傳遞", "等溫、絕熱等過程分析", "絕熱過程 Q = 0"] }
      ]
    },
    {
      no: "八", id: "waves", title: "波動與聲音", track: "必修 · 選修波動光學", color: "#7986cb",
      intro: "橫波與縱波的性質、波的疊加與干涉、駐波、都卜勒效應、拍與聲音的共鳴。",
      experiments: [
        { id: "wave-types", title: "橫波與縱波", interactive: I,
          concept: "介質振動方向與波前進方向垂直者為橫波、平行者為縱波。調整頻率與振幅，觀察質點振動與波形前進的關係。",
          formula: R`\( v = f\lambda,\quad T = \dfrac{1}{f} \)`,
          points: ["繩波為橫波", "聲波為縱波", "波速由介質決定", "質點振動 vs 波形移動"] },
        { id: "superposition", title: "波的疊加與干涉", interactive: I,
          concept: "兩波相遇時位移相加；相位相同則相長、相反則相消。調整兩波相位差，觀察合成波的相長與相消。",
          formula: R`\( \text{相長：}\Delta = n\lambda,\quad \text{相消：}\Delta = (n+\tfrac{1}{2})\lambda \)`,
          points: ["重疊原理", "相長與相消干涉", "路徑差決定干涉結果", "水波槽實驗"] },
        { id: "standing-wave", title: "弦上的駐波", interactive: I,
          concept: "兩列同頻率、反向前進的波疊加形成駐波；弦上只能存在特定的共振頻率（諧波）。切換諧波階數觀察波節與波腹。",
          formula: R`\( L = n\dfrac{\lambda}{2},\quad f_n = \dfrac{nv}{2L},\quad n = 1,2,3\ldots \)`,
          points: ["波節不動波腹振幅最大", "只有特定頻率能共振", "n = 1 為基頻", "頻率為基頻整數倍"] },
        { id: "doppler", title: "都卜勒效應", interactive: I,
          concept: "波源與觀察者相對運動時，觀察到的頻率改變；接近時變高、遠離時變低。移動波源，觀察前後波長被壓縮與拉長。",
          formula: R`\( f' = f\,\dfrac{v \pm v_o}{v \mp v_s} \)`,
          points: ["接近時頻率升高", "遠離時頻率降低", "波源前方波長被壓縮", "測速與天文紅移"] },
        { id: "beats", title: "拍", interactive: I,
          concept: "兩個頻率相近的波疊加時，合成振幅週期性強弱變化形成拍；拍頻等於兩頻率之差。調整兩頻率觀察拍的快慢。",
          formula: R`\( f_{\text{拍}} = |f_1 - f_2| \)`,
          points: ["頻率相近才聽得到拍", "拍頻 = 頻率差", "調音的原理", "振幅週期性起伏"] },
        { id: "resonance-tube", title: "聲音的共鳴（共鳴管）", interactive: I,
          concept: "空氣柱在特定長度時與音叉產生共鳴，可測聲速。調整管長，觀察開管與閉管的共鳴位置與諧波差異。",
          formula: R`\( \text{開管 } f_n = \dfrac{nv}{2L},\quad \text{閉管 } f_n = \dfrac{(2n-1)v}{4L} \)`,
          points: ["共鳴時振幅最大", "開管含全部諧波", "閉管只含奇次諧波", "可用來測聲速"] }
      ]
    },
    {
      no: "九", id: "optics", title: "光學", track: "必修 · 選修波動光學", color: "#f06292",
      intro: "光的反射與折射、面鏡與透鏡成像，以及干涉、繞射、偏振與色散等波動性質。",
      experiments: [
        { id: "snell", title: "反射與折射（司乃耳定律）", interactive: I,
          concept: "光由一介質進入另一介質時偏折，入射角與折射角遵循司乃耳定律；由密到疏超過臨界角則全反射。拖動入射角觀察。",
          formula: R`\( n_1\sin\theta_1 = n_2\sin\theta_2,\quad \theta_c = \sin^{-1}\!\dfrac{n_2}{n_1} \)`,
          points: ["反射角等於入射角", "折射率決定偏折量", "由疏入密偏向法線", "全反射與臨界角"] },
        { id: "mirror", title: "面鏡成像", interactive: I,
          concept: "凹面鏡與凸面鏡依物距形成不同性質的像；用主要光線作圖找像。移動物體，觀察像的正立/倒立、放大/縮小、虛/實。",
          formula: R`\( \dfrac{1}{f} = \dfrac{1}{p} + \dfrac{1}{q},\quad m = -\dfrac{q}{p},\quad f = \dfrac{R}{2} \)`,
          points: ["凹面鏡可成實像或虛像", "凸面鏡恆成縮小虛像", "焦距 f = R/2", "主要光線作圖法"] },
        { id: "lens", title: "透鏡成像", interactive: I,
          concept: "凸透鏡與凹透鏡依物距形成不同的像；用三條主要光線作圖找像。移動物體，觀察成像規律與應用。",
          formula: R`\( \dfrac{1}{f} = \dfrac{1}{p} + \dfrac{1}{q},\quad m = -\dfrac{q}{p} \)`,
          points: ["凸透鏡會聚光線", "凹透鏡發散光線", "物在 2f 外成縮小倒立實像", "近視與遠視矯正"] },
        { id: "double-slit", title: "雙縫干涉", interactive: I,
          concept: "同調光通過雙狹縫後在屏幕上形成明暗相間的干涉條紋，證明光具有波動性。調整縫距與波長觀察條紋間距。",
          formula: R`\( d\sin\theta = m\lambda,\quad \Delta y = \dfrac{\lambda L}{d} \)`,
          points: ["亮紋：路程差為 λ 整數倍", "縫距越小條紋越寬", "波長越長條紋越寬", "楊氏實驗證明波動性"] },
        { id: "diffraction", title: "單狹縫繞射", interactive: I,
          concept: "光通過單狹縫會繞射展開，形成中央最寬最亮、兩側逐漸變暗的繞射圖樣。調整縫寬與波長觀察中央亮紋寬度。",
          formula: R`\( a\sin\theta = m\lambda\ (m=1,2,\ldots\text{為暗紋}) \)`,
          points: ["繞射使光偏離直線", "中央亮紋最寬最亮", "縫越窄繞射越明顯", "解析度的極限"] },
        { id: "polarization", title: "偏振", interactive: I,
          concept: "偏振顯示光為橫波；自然光通過偏振片後只剩單一振動方向，再通過第二片時強度依馬呂士定律變化。旋轉偏振片觀察。",
          formula: R`\( I = I_0\cos^2\theta \)`,
          points: ["偏振證明光為橫波", "馬呂士定律 I = I₀cos²θ", "兩片垂直時全暗", "偏光太陽眼鏡應用"] },
        { id: "dispersion", title: "色散與稜鏡", interactive: I,
          concept: "介質折射率隨波長不同，使白光經稜鏡分解成彩色光譜；紫光偏折最多、紅光最少。調整入射角觀察分光。",
          formula: R`\( n_{\text{紫}} > n_{\text{紅}} \;\Rightarrow\; \theta_{\text{紫}} > \theta_{\text{紅}} \)`,
          points: ["折射率隨波長改變", "紫光偏折最多", "白光分解為光譜", "彩虹的成因"] }
      ]
    },
    {
      no: "十", id: "electric", title: "電場與電路", track: "必修 · 選修電磁學", color: "#4db6ac",
      intro: "庫侖定律、電場與電位、電容器，以及歐姆定律、電阻串並聯與電路分析。",
      experiments: [
        { id: "coulomb", title: "庫侖定律", interactive: I,
          concept: "兩點電荷間的靜電力與電量乘積成正比、與距離平方成反比，同性相斥、異性相吸。調整電量與距離觀察靜電力。",
          formula: R`\( F = k\dfrac{q_1 q_2}{r^2},\quad k = 9\times10^{9}\ \mathrm{N\,m^2/C^2} \)`,
          points: ["同性相斥異性相吸", "平方反比定律", "與萬有引力形式相同", "距離加倍力變 1/4"] },
        { id: "efield", title: "電場線與等勢面", interactive: I,
          concept: "電荷在周圍空間產生電場，以電場線表示方向與強弱；與電場線垂直者為等勢面。拖動電荷觀察電場線與等勢面。",
          formula: R`\( E = \dfrac{kQ}{r^2},\quad V = \dfrac{kQ}{r} \)`,
          points: ["電場線由正電荷指向負電荷", "電場線密處場強大", "等勢面與電場線垂直", "沿等勢面移動不做功"] },
        { id: "potential-e", title: "電位與電位能", interactive: I,
          concept: "單位電荷在電場中所具有的位能為電位（純量）。在均勻電場中移動試驗電荷，觀察電位差、電場與作功的關係。",
          formula: R`\( V = \dfrac{U}{q},\quad E = \dfrac{V}{d},\quad W = q\,\Delta V \)`,
          points: ["電位差驅動電流", "沿電場方向電位下降", "等勢面電位相同", "單位為伏特"] },
        { id: "ohms", title: "歐姆定律與電路", interactive: I,
          concept: "導體兩端電壓與電流成正比，比值為電阻。調整電壓與電阻，觀察電流與功率如何變化。",
          formula: R`\( V = IR,\quad P = IV = I^2R = \dfrac{V^2}{R} \)`,
          points: ["電阻阻礙電流", "V 與 I 成正比", "功率 P = IV", "電阻發熱效應"] },
        { id: "resistors", title: "電阻的串聯與並聯", interactive: I,
          concept: "串聯電阻相加、電流相同；並聯電阻倒數相加、電壓相同。切換接法，觀察等效電阻、分壓與分流。",
          formula: R`\( R_s = \sum R_i,\quad \dfrac{1}{R_p} = \sum \dfrac{1}{R_i} \)`,
          points: ["串聯分壓電流相同", "並聯分流電壓相同", "並聯總電阻比任一支路小", "電流走捷徑（低阻）"] },
        { id: "capacitor", title: "電容器充放電", interactive: I,
          concept: "電容器透過電阻充放電時，電壓與電流呈指數變化，時間常數 τ = RC 決定快慢。切換充放電觀察指數曲線。",
          formula: R`\( C = \dfrac{Q}{V},\quad \tau = RC,\quad V = V_0(1-e^{-t/\tau}) \)`,
          points: ["電容器儲存電荷與電能", "時間常數 τ = RC", "充電電壓指數上升", "放電電流指數衰減"] }
      ]
    },
    {
      no: "十一", id: "magnetism", title: "磁場與電磁感應", track: "必修 · 選修電磁學", color: "#9575cd",
      intro: "載流導線的磁場、勞侖茲力、法拉第電磁感應與楞次定律，以及交流發電機與變壓器。",
      experiments: [
        { id: "current-field", title: "載流導線的磁場", interactive: I,
          concept: "電流在周圍產生磁場，方向由安培右手定則決定，直線導線的磁場與距離成反比。調整電流觀察磁場方向與強弱。",
          formula: R`\( \text{直線 } B = \dfrac{\mu_0 I}{2\pi r},\quad \text{螺線管 } B = \mu_0 n I \)`,
          points: ["電流磁效應", "安培右手定則", "磁場繞導線成圓", "電磁鐵原理"] },
        { id: "lorentz", title: "磁場與勞侖茲力", interactive: I,
          concept: "運動電荷在磁場中受力，方向由右手定則決定；力恆垂直速度，使帶電粒子作等速率圓周運動。調整速度與磁場觀察半徑。",
          formula: R`\( F = qvB\sin\theta,\quad r = \dfrac{mv}{qB},\quad T = \dfrac{2\pi m}{qB} \)`,
          points: ["力垂直速度與磁場", "帶電粒子作圓周運動", "半徑與動量成正比", "週期與速率無關"] },
        { id: "induction", title: "電磁感應（法拉第定律）", interactive: I,
          concept: "磁通量改變會在線圈感應出電動勢；變化越快電動勢越大。移動磁鐵穿過線圈，觀察感應電流的產生與方向。",
          formula: R`\( \varepsilon = -N\dfrac{\Delta\Phi}{\Delta t},\quad \Phi = BA\cos\theta \)`,
          points: ["磁通量變化才有感應電流", "變化越快電動勢越大", "楞次定律定方向", "發電機的基本原理"] },
        { id: "lenz", title: "楞次定律", interactive: I,
          concept: "感應電流的磁場總是反抗原磁通量的變化，體現能量守恆。觀察磁鐵接近與遠離時感應電流方向如何反抗運動。",
          formula: R`\( \varepsilon = -N\dfrac{d\Phi}{dt} \)`,
          points: ["反抗磁通變化", "能量守恆的展現", "電磁煞車應用", "感應電流方向的判準"] },
        { id: "ac-generator", title: "交流發電機", interactive: I,
          concept: "線圈在均勻磁場中轉動，使磁通量週期變化，感應出正弦式交流電動勢。調整轉速，觀察感應電動勢的波形。",
          formula: R`\( \varepsilon = \varepsilon_0\sin(\omega t),\quad \varepsilon_0 = NBA\omega \)`,
          points: ["旋轉線圈產生交流電", "電動勢隨轉速增大", "磁通與電動勢相位差 90°", "發電廠的核心"] },
        { id: "transformer", title: "變壓器", interactive: I,
          concept: "利用電磁感應改變交流電壓，電壓比等於匝數比；理想變壓器功率守恆。調整匝數比，觀察升壓/降壓與電流的反向變化。",
          formula: R`\( \dfrac{V_s}{V_p} = \dfrac{N_s}{N_p},\quad V_pI_p = V_sI_s \)`,
          points: ["電壓比 = 匝數比", "升壓則降流", "理想變壓器功率守恆", "高壓輸電降低損耗"] }
      ]
    },
    {
      no: "十二", id: "modern", title: "近代物理與宇宙學", track: "必修 · 選修近代物理", color: "#ffb74d",
      intro: "光電效應、原子模型、物質波、狹義相對論、原子核與放射性，以及大霹靂與宇宙膨脹。",
      experiments: [
        { id: "photoelectric", title: "光電效應", interactive: I,
          concept: "光照射金屬時若頻率足夠高即射出電子；光以光子形式攜帶能量，證明光的粒子性。調整頻率與光強觀察光電子。",
          formula: R`\( E = hf,\quad hf = W + K_{max},\quad K_{max} = hf - W \)`,
          points: ["需超過底限頻率才有電子", "增加光強只增加電子數", "光子能量與頻率成正比", "愛因斯坦以此獲諾貝爾獎"] },
        { id: "bohr", title: "波耳原子模型與原子光譜", interactive: I,
          concept: "電子只能在特定能階運行，躍遷時吸收或放出特定頻率的光，形成不連續的原子光譜。切換能階觀察躍遷與譜線。",
          formula: R`\( E_n = -\dfrac{13.6}{n^2}\ \mathrm{eV},\quad \Delta E = hf = \dfrac{1240}{\lambda[\mathrm{nm}]} \)`,
          points: ["能階量子化", "躍遷放出特定波長的光", "萊曼系（紫外）、巴耳末系（可見）", "解釋氫原子光譜"] },
        { id: "matter-wave", title: "物質波（德布羅意）", interactive: I,
          concept: "運動的粒子也具有波動性，波長與動量成反比。調整粒子速度與質量，觀察物質波波長與電子繞射。",
          formula: R`\( \lambda = \dfrac{h}{p} = \dfrac{h}{mv} \)`,
          points: ["波粒二象性", "電子繞射實驗證實", "速度越大波長越短", "電子顯微鏡原理"] },
        { id: "relativity", title: "狹義相對論", interactive: I,
          concept: "接近光速時時間膨脹、長度收縮；用光鐘可看出運動時鐘走得較慢。調整速度觀察時間膨脹因子 γ 的變化。",
          formula: R`\( \gamma = \dfrac{1}{\sqrt{1 - v^2/c^2}},\quad t = \gamma t_0,\quad E = mc^2 \)`,
          points: ["光速為恆定上限", "時間膨脹與長度收縮", "質能等價 E = mc²", "v→c 時 γ→∞"] },
        { id: "halflife", title: "原子核與放射性半衰期", interactive: I,
          concept: "不穩定原子核放出 α、β、γ 射線而衰變，每經一個半衰期數量減半。調整半衰期，觀察衰變曲線與剩餘核數。",
          formula: R`\( N = N_0\left(\tfrac{1}{2}\right)^{t/T_{1/2}} \)`,
          points: ["三種放射線性質不同", "半衰期為統計特性", "每半衰期數量減半", "碳-14 定年法"] },
        { id: "hubble", title: "大霹靂與哈伯定律", interactive: I,
          concept: "宇宙起源於大霹靂並持續膨脹，遠方星系退行速度與距離成正比。調整哈伯常數，觀察星系退行與紅移。",
          formula: R`\( v = H_0 d,\quad H_0 \approx 70\ \mathrm{km/s/Mpc} \)`,
          points: ["宇宙膨脹", "退行速度與距離成正比", "紅移現象", "宇宙微波背景輻射"] }
      ]
    }
  ];

  let expCount = 0, interactiveCount = 0;
  MODULES.forEach(m => m.experiments.forEach(e => { expCount++; if (e.interactive) interactiveCount++; }));

  window.PhysicsLabCurriculum = {
    modules: MODULES,
    totalModules: MODULES.length,
    totalExperiments: expCount,
    totalInteractive: interactiveCount
  };
})();
