/*
 * curriculum.js
 * 物理實驗室 — 課程結構資料
 * 依教育部 108 課綱「自然科學領域—物理」規劃，涵蓋必修物理與選修物理（加深加廣）。
 * 基礎與第二批課程地圖：12 個學習模組 · 120 個實驗主題；第三、四批延伸主題分別由 advanced-curriculum.js 與 comprehensive-curriculum.js 載入。
 * 公式以 LaTeX 撰寫（String.raw 保留反斜線），由 MathJax 排版。
 * 本檔為原創教材資料，物理模型為教學簡化版，數值以概念示範為主。
 */
(function () {
  "use strict";
  const R = String.raw;
  const I = true; // 所有實驗皆為互動模擬

  const MODULES = [
    {
      no: "一", id: "kinematics", title: "運動學", track: "必修 · 選修力學一", color: "#4dd0e1",
      intro: "描述物體如何運動——位置、位移、速度與加速度，等加速度運動、自由落體、拋體運動與相對運動。",
      experiments: [
        { id: "uniform-accel", title: "等加速度直線運動", interactive: I,
          concept: "加速度固定時，速度隨時間線性變化，位移為 v–t 圖下的面積。調整初速與加速度，觀察 x–t 與 v–t 圖如何改變。",
          formula: R`\( v = v_0 + at,\quad s = v_0 t + \tfrac{1}{2}at^2,\quad v^2 = v_0^2 + 2as \)`,
          points: ["v–t 圖斜率為加速度", "v–t 圖面積為位移", "三大等加速度運動公式", "a 為負代表減速"] },
        { id: "freefall", title: "自由落體", interactive: I,
          concept: "只受重力作用的落體是等加速度運動的特例（a = g）；落地時間與速率只與高度和 g 有關，與質量無關。",
          formula: R`\( v = gt,\quad h = \tfrac{1}{2}gt^2,\quad v = \sqrt{2gh},\quad g \approx 9.8\ \mathrm{m/s^2} \)`,
          points: ["初速為零由靜止落下", "落地速率與 √高度 成正比", "與物體質量無關", "v–t 圖為過原點直線"] },
        { id: "projectile", title: "拋體運動", interactive: I,
          concept: "拋體同時進行水平等速度與鉛直等加速度運動；兩方向彼此獨立。改變發射角與初速觀察射程與最大高度。",
          formula: R`\( x = v_0\cos\theta\,t,\quad y = v_0\sin\theta\,t - \tfrac{1}{2}gt^2,\quad R = \dfrac{v_0^2\sin 2\theta}{g} \)`,
          points: ["水平方向速度分量固定", "鉛直方向為自由落體", "45° 在平地射程最遠", "軌跡為拋物線"] },
        { id: "relative-motion", title: "相對運動與參考系", interactive: I,
          concept: "速度會隨觀察者所在參考系而不同，可用向量相加求相對速度。以過河船為例，調整船速與水流觀察合速度與漂移。",
          formula: R`\( \vec{v}_{A/B} = \vec{v}_{A} - \vec{v}_{B},\quad v = \sqrt{v_x^2 + v_y^2} \)`,
          points: ["選定參考系是描述運動的前提", "相對速度為向量差", "過河最短時間 vs 最短路徑", "常見於船渡河、飛機遇風"] },
        { id: "vt-graph", title: "運動圖形分析", interactive: I,
          concept: "同一段運動可用 x–t、v–t、a–t 三種圖形描述；斜率與面積把三者連結起來。拖動控制點即時比較三圖。",
          formula: R`\( v = \dfrac{dx}{dt},\quad a = \dfrac{dv}{dt},\quad \Delta x = \int v\,dt \)`,
          points: ["x–t 斜率為速度", "v–t 斜率為加速度", "v–t 面積為位移", "圖形是運動的語言"] },
        { id: "ticker-tape", title: "打點計時器（測速度與加速度）", interactive: I,
          concept: "打點計時器每隔固定時間在紙帶上打一點，點距越來越大代表在加速。相鄰點距除以時間得瞬時速度、點距的變化量得加速度——最經典的運動學實驗。",
          formula: R`\( \bar{v}_n = \dfrac{x_{n+1}-x_{n-1}}{2T},\quad a = \dfrac{\Delta(\Delta x)}{T^2} \)`,
          points: ["每點間隔時間 T 固定", "點距 = 平均速度 × T", "點距等差增加代表等加速", "由紙帶可反推 v–t 圖"] }
      ]
    },
    {
      no: "二", id: "newton", title: "牛頓運動定律與力", track: "必修 · 選修力學一", color: "#ff8a65",
      intro: "力如何改變運動狀態——慣性、F = ma、作用與反作用，以及斜面、摩擦、張力與連接體問題。",
      experiments: [
        { id: "inertia", title: "慣性與牛頓第一運動定律", interactive: I,
          concept: "不受外力（或合力為零）的物體維持原有運動狀態。改變摩擦係數，觀察滑塊因慣性繼續前進的距離。",
          formula: R`\( \sum \vec{F} = 0 \;\Rightarrow\; \vec{v} = \text{定值} \)`,
          points: ["物體傾向保持原狀態", "慣性大小由質量決定", "無摩擦則永遠等速前進", "安全帶與慣性"] },
        { id: "newton2", title: "牛頓第二運動定律 F = ma", interactive: I,
          concept: "物體加速度與合力成正比、與質量成反比，方向與合力相同。施加不同的力與質量，觀察加速度變化。",
          formula: R`\( \sum \vec{F} = m\vec{a},\quad a = \dfrac{F}{m} \)`,
          points: ["合力決定加速度", "質量是慣性的量度", "1 N = 1 kg·m/s²", "同力下質量越大越難加速"] },
        { id: "incline", title: "斜面上的物體受力", interactive: I,
          concept: "斜面上的物體受重力、正向力與摩擦力；將重力沿斜面與垂直斜面分解可求加速度。調整角度與摩擦觀察下滑或靜止。",
          formula: R`\( mg\sin\theta - \mu mg\cos\theta = ma,\quad N = mg\cos\theta \)`,
          points: ["重力分解為 mg sinθ 與 mg cosθ", "靜摩擦最大值 = μₛN", "θ 增大下滑加速度增大", "μ > tanθ 時靜止"] },
        { id: "incline-applied-force", title: "斜面外力與摩擦力方向", interactive: I,
          concept: "斜面上的物體若受到沿斜面的推力或拉力，摩擦力方向必須抵抗『相對滑動趨勢』。改變外力大小與方向，觀察靜摩擦力何時向上、向下或不足以維持靜止。",
          formula: R`\( N=mg\cos\theta,\quad |f_s|\le\mu_sN,\quad \sum F_{\parallel}=ma \)`,
          points: ["先比較重力分量與外力，找出滑動趨勢", "摩擦力方向不固定，永遠反抗相對滑動", "靜摩擦力大小由平衡需要決定", "超過最大靜摩擦才會開始滑動"] },
        { id: "table-hanger", title: "桌面—懸掛連接體", interactive: I,
          concept: "桌上的物體以細繩越過滑輪連接懸掛砝碼時，可先視兩物體為整體判斷是否靜止，再以個別受力圖求繩張力。調整兩端質量與摩擦係數，找出開始運動的臨界條件。",
          formula: R`\( m_hg-f= (m_t+m_h)a,\quad T=m_ta+f \)`,
          points: ["先確認懸掛重力能否克服最大靜摩擦", "運動時使用動摩擦力", "理想繩兩端張力相同", "整體法求 a，隔離法求 T"] },
        { id: "rope-over-edge", title: "桌邊垂落繩的加速度", interactive: I,
          concept: "均勻繩一部分放在光滑桌面、一部分垂在桌邊時，只有垂落部分的重力提供拉力；整條繩都要一起加速。改變垂落比例，觀察加速度如何變化。",
          formula: R`\( (\lambda x)g=(\lambda L)a,\quad a=\dfrac{x}{L}g \)`,
          points: ["驅動力只來自垂落部分重量", "慣性質量是整條繩的質量", "垂落比例越大，加速度越大", "可用整體法避免重複計算張力"] },
        { id: "friction", title: "靜摩擦與動摩擦", interactive: I,
          concept: "接觸面阻礙相對運動的力，靜摩擦可變且有最大值，物體開始滑動後轉為近似定值的動摩擦。拉動拉力觀察臨界點。",
          formula: R`\( f_s \le \mu_s N,\quad f_k = \mu_k N,\quad \mu_s > \mu_k \)`,
          points: ["靜摩擦隨外力增大", "超過最大靜摩擦即滑動", "動摩擦近似定值", "μ 與接觸面性質有關"] },
        { id: "wall-friction", title: "牆面靜摩擦力判讀", interactive: I,
          concept: "用水平力把物體壓在粗糙的鉛直牆面上時，正向力等於推力；若物體靜止，靜摩擦力恰好平衡重力，而不是一律等於 μₛN。調整推力，找出剛好不下滑的臨界條件。",
          formula: R`\( N=F,\quad f_s=mg\ (\text{靜止時}),\quad f_{s,\max}=\mu_sF,\quad F_{\min}=\dfrac{mg}{\mu_s} \)`,
          points: ["靜止時 fₛ = mg，不隨推力任意增加", "推力決定正向力與最大靜摩擦", "剛好不下滑時 μₛF = mg", "靜摩擦不足才會向下滑動"] },
        { id: "stacked-block-friction", title: "疊放物體的靜摩擦力", interactive: I,
          concept: "推動下方物體時，上方物體靠靜摩擦力一起加速。摩擦力方向由相對滑動趨勢決定，大小則剛好提供上方物體所需的加速度；不足時兩物體才會相對滑動。",
          formula: R`\( a=\dfrac{F}{m_1+m_2},\quad f_{\text{需要}}=m_1a,\quad f_{s,\max}=\mu_sm_1g \)`,
          points: ["上方物體有向後滑動趨勢，受摩擦力向前", "靜摩擦力不必等於 μₛN", "先以整體求共同加速度", "f需要超過最大靜摩擦才會滑動"] },
        { id: "two-rope-equilibrium", title: "兩繩懸掛與三力平衡", interactive: I,
          concept: "重物經由兩條繩子懸掛時，繩張力的水平分量互相平衡、鉛直分量合起來平衡重力。改變兩繩角度，觀察繩子越水平時張力為何急遽增加。",
          formula: R`\( \sum F_x=0,\quad \sum F_y=0,\quad T_L=\dfrac{mg\cos\theta_R}{\sin(\theta_L+\theta_R)} \)`,
          points: ["平衡條件是各方向合力為零", "張力方向沿繩子", "繩子越平，張力越大", "可用分量或力的平行四邊形分析"] },
        { id: "conveyor-friction", title: "輸送帶上的摩擦力方向", interactive: I,
          concept: "物體放到移動中的輸送帶後，摩擦力總是抵抗兩者的相對滑動。比較輸送帶與物體的速度，判讀摩擦力方向、物體加速度與最後同速的時刻。",
          formula: R`\( f_k=\mu_kmg,\quad a=\dfrac{f_k}{m}=\mu_kg,\quad v(t)=v_0+at \)`,
          points: ["摩擦力方向看相對運動，不只看物體向哪裡移動", "物體比帶慢時，摩擦力拉著物體前進", "物體比帶快時，摩擦力使物體減速", "同速後不再有相對滑動"] },
        { id: "atwood", title: "連接體與張力（阿特午機）", interactive: I,
          concept: "以繩連接的兩物體可視為整體求加速度，再對個別物體求繩張力。改變兩端質量觀察系統的運動與張力。",
          formula: R`\( a = \dfrac{(m_1-m_2)g}{m_1+m_2},\quad T = \dfrac{2m_1 m_2 g}{m_1+m_2} \)`,
          points: ["整體法求加速度", "隔離法求繩張力", "理想繩張力處處相等", "質量相等時系統靜止"] },
        { id: "newton3", title: "牛頓第三運動定律", interactive: I,
          concept: "作用力與反作用力大小相等、方向相反，且作用在不同物體上，故不會抵消。以兩人推牆或火箭示範作用—反作用對。",
          formula: R`\( \vec{F}_{AB} = -\vec{F}_{BA} \)`,
          points: ["成對出現", "作用在不同物體不抵消", "與物體質量無關", "反衝與推進的基礎"] },
        { id: "torque-equilibrium", title: "力矩與靜力平衡", interactive: I,
          concept: "力矩衡量力使物體轉動的效果，等於力乘以力臂；當順時針與逆時針力矩相等時，物體達成靜力平衡（如天平、槓桿）。調整兩側質量與力臂觀察平衡與傾斜。",
          formula: R`\( \tau = F d,\quad \sum \tau_{\text{順}} = \sum \tau_{\text{逆}} \)`,
          points: ["力矩 = 力 × 力臂", "力臂為支點到作用線的垂直距離", "合力矩為零才平衡", "槓桿與天平原理"] },
        { id: "force-table", title: "力的合成與分解（力桌）", interactive: I,
          concept: "在力桌上以繩與砝碼施加數個共點力，改變大小與方向，觀察合力（向量和）與能使系統平衡的平衡力——平衡力與合力等大反向。",
          formula: R`\( \vec{F}_{\text{合}} = \vec{F}_1 + \vec{F}_2,\quad \vec{F}_{\text{平衡}} = -\vec{F}_{\text{合}} \)`,
          points: ["力是向量，依平行四邊形相加", "合力可分解為兩垂直分量", "平衡力與合力等大反向", "三力平衡則首尾相接成封閉三角形"] },
        { id: "hookes-law", title: "虎克定律與彈簧", interactive: I,
          concept: "在彈性限度內，彈簧伸長量與所受拉力成正比，比例常數即彈簧勁度 k。掛不同砝碼量測伸長，F–x 圖為過原點的直線，斜率就是 k。",
          formula: R`\( F = kx,\quad k = \dfrac{F}{x} \)`,
          points: ["伸長量與外力成正比", "F–x 圖斜率為勁度 k", "超過彈性限度不再成立", "串聯變軟、並聯變硬"] }
      ]
    },
    {
      no: "三", id: "momentum", title: "動量與碰撞", track: "選修力學一", color: "#ba68c8",
      intro: "動量、衝量與碰撞——沒有外力時系統總動量守恆，彈性碰撞另滿足動能守恆。",
      experiments: [
        { id: "collision", title: "一維碰撞", interactive: I,
          concept: "兩物體碰撞時系統總動量守恆；彈性碰撞另滿足動能守恆，非彈性碰撞則有動能損失。調整回復係數觀察碰後速度。",
          formula: R`\( m_1u_1 + m_2u_2 = m_1v_1 + m_2v_2,\quad e = \dfrac{v_2-v_1}{u_1-u_2} \)`,
          points: ["動量恆守恆", "彈性碰撞動能不變", "完全非彈性碰後合為一體", "回復係數 e 介於 0 與 1"] },
        { id: "momentum-cons", title: "動量守恆定律", interactive: I,
          concept: "系統不受外力（或外力和為零）時，總動量保持不變，源自牛頓第三定律。觀察碰撞前後總動量向量恆定。",
          formula: R`\( \sum \vec{p} = \sum m\vec{v} = \text{定值} \)`,
          points: ["源自牛頓第三定律", "向量式守恆", "適用碰撞、爆炸、反衝", "外力衝量改變總動量"] },
        { id: "impulse", title: "衝量與動量定理", interactive: I,
          concept: "力對時間的累積（衝量）等於動量的變化量。改變作用時間，觀察相同動量變化下所需的力如何不同。",
          formula: R`\( \vec{J} = \int \vec{F}\,dt = \Delta \vec{p},\quad F_{avg} = \dfrac{\Delta p}{\Delta t} \)`,
          points: ["衝量為力–時間圖面積", "延長作用時間可減小衝擊力", "安全氣囊與緩衝墊原理", "衝量與動量同單位"] },
        { id: "collision2d", title: "二維碰撞", interactive: I,
          concept: "平面碰撞時 x、y 兩方向動量各自守恆。調整入射角與瞄準參數，觀察兩球碰後分飛的方向。",
          formula: R`\( \sum p_x = \text{定值},\quad \sum p_y = \text{定值} \)`,
          points: ["各分量獨立守恆", "等質量彈性碰撞後夾 90°", "撞球檯上的應用", "瞄準參數決定散射角"] },
        { id: "recoil", title: "反衝與爆炸", interactive: I,
          concept: "靜止系統分裂時各部分動量大小相等、方向相反，總動量仍為零。示範槍枝後座與火箭推進。",
          formula: R`\( 0 = m_1v_1 + m_2v_2,\quad v_1 = -\dfrac{m_2}{m_1}v_2 \)`,
          points: ["火箭推進原理", "槍枝後座力", "總動量守恆為零", "質量小者速度大"] },
        { id: "ballistic-pendulum", title: "彈道擺", interactive: I,
          concept: "子彈射入懸掛的木塊並嵌入，再一起擺高。碰撞瞬間動量守恆求合體速度，之後力學能守恆求上升高度——可反推子彈初速，是動量與能量的經典綜合題。",
          formula: R`\( mv = (m+M)V,\quad V = \sqrt{2gh},\quad v = \dfrac{m+M}{m}\sqrt{2gh} \)`,
          points: ["碰撞（嵌入）動量守恆", "碰撞後力學能才守恆", "碰撞中動能有損失", "由上升高度反推子彈速率"] }
      ]
    },
    {
      no: "四", id: "energy", title: "功與能量", track: "必修 · 選修力學一", color: "#81c784",
      intro: "功、動能與位能——力學能守恆，功率、功能定理與保守力的概念。",
      experiments: [
        { id: "work-power", title: "功與功率", interactive: I,
          concept: "力沿位移方向所做的功，以及做功的快慢（功率）。改變施力大小與方向角，觀察有效作功與功率。",
          formula: R`\( W = Fs\cos\theta,\quad P = \dfrac{W}{t} = Fv \)`,
          points: ["功是純量", "垂直方向的力不做功", "1 W = 1 J/s", "功率為作功速率"] },
        { id: "work-energy", title: "功能定理", interactive: I,
          concept: "合力對物體所做的淨功等於其動能的變化。對滑塊施力一段距離，觀察速度與動能如何隨淨功增加。",
          formula: R`\( W_{net} = \Delta K = \tfrac{1}{2}mv^2 - \tfrac{1}{2}mv_0^2 \)`,
          points: ["淨功改變動能", "連結力與運動", "適用變力問題", "負功使物體減速"] },
        { id: "energy-track", title: "軌道上的力學能守恆", interactive: I,
          concept: "無摩擦軌道上動能與重力位能互相轉換，但力學能總和不變；加入摩擦則力學能逐漸轉為熱。調整起始高度與摩擦。",
          formula: R`\( E = K + U = \tfrac{1}{2}mv^2 + mgh = \text{定值} \)`,
          points: ["最高點位能最大動能最小", "最低點動能最大", "有摩擦力學能轉熱能", "能量守恆是核心概念"] },
        { id: "potential", title: "重力位能與彈性位能", interactive: I,
          concept: "物體因位置或形變而儲存的能量。壓縮彈簧再釋放，觀察彈性位能轉為動能再轉為重力位能。",
          formula: R`\( U_g = mgh,\quad U_s = \tfrac{1}{2}kx^2 \)`,
          points: ["位能與參考點有關", "彈性位能與形變平方成正比", "皆為保守力位能", "位能可完全轉為動能"] },
        { id: "conservative", title: "保守力與非保守力", interactive: I,
          concept: "保守力做功與路徑無關；非保守力（如摩擦）會消耗力學能。比較同一物體走不同路徑時力學能的變化。",
          formula: R`\( W_{\text{保守}} = -\Delta U,\quad \oint \vec{F}_{\text{保守}}\cdot d\vec{r} = 0 \)`,
          points: ["重力、彈力為保守力", "摩擦力為非保守力", "保守力做功只看起訖點", "非保守力使力學能不守恆"] }
      ]
    },
    {
      no: "五", id: "gravity", title: "圓周運動與萬有引力", track: "必修 · 選修力學一", color: "#ffd54f",
      intro: "等速圓周運動與向心力，牛頓萬有引力、人造衛星、克卜勒行星運動定律與角動量守恆。",
      experiments: [
        { id: "circular", title: "等速圓周運動", interactive: I,
          concept: "沿圓周等速率運動時，加速度指向圓心；速率不變但速度方向持續改變。調整半徑與角速度觀察速度與加速度向量。",
          formula: R`\( a_c = \dfrac{v^2}{r} = \omega^2 r,\quad v = \omega r,\quad T = \dfrac{2\pi r}{v} \)`,
          points: ["速率不變速度方向改變", "向心加速度指向圓心", "週期與角速度成反比", "速度恆與半徑垂直"] },
        { id: "centripetal", title: "向心力", interactive: I,
          concept: "維持圓周運動所需、指向圓心的合力。以繩繫小球旋轉為例，觀察張力如何隨速率與半徑改變，並示範脫離時的切線飛出。",
          formula: R`\( F_c = \dfrac{mv^2}{r} = m\omega^2 r \)`,
          points: ["向心力指向圓心", "由張力/重力/摩擦等提供", "斷繩後沿切線飛出", "與 v² 成正比"] },
        { id: "gravitation", title: "萬有引力定律", interactive: I,
          concept: "任兩質點相互吸引，力與質量乘積成正比、與距離平方成反比。改變距離觀察引力的平方反比變化。",
          formula: R`\( F = G\dfrac{m_1 m_2}{r^2},\quad g = \dfrac{GM}{R^2},\quad G = 6.67\times10^{-11} \)`,
          points: ["平方反比定律", "解釋重力與天體運動", "距離加倍引力變 1/4", "g 隨高度減小"] },
        { id: "orbit", title: "行星軌道與克卜勒定律", interactive: I,
          concept: "行星在萬有引力作用下沿橢圓軌道繞恆星運行，掃過的面積速率固定。調整初速觀察圓、橢圓、拋物線軌道的轉變。",
          formula: R`\( F = \dfrac{GMm}{r^2},\quad T^2 \propto a^3,\quad \dfrac{dA}{dt}=\text{定值} \)`,
          points: ["軌道為橢圓恆星在焦點", "近日點速度較快（等面積律）", "週期平方與半長軸立方成正比", "向心力由萬有引力提供"] },
        { id: "satellite", title: "人造衛星與脫離速度", interactive: I,
          concept: "衛星以萬有引力為向心力繞行；達到脫離速度即可擺脫引力束縛。調整發射速率觀察繞行、脫離或墜落。",
          formula: R`\( v_{\text{軌道}} = \sqrt{\dfrac{GM}{r}},\quad v_{\text{脫離}} = \sqrt{\dfrac{2GM}{R}} \)`,
          points: ["近地軌道速率約 7.9 km/s", "脫離速率約 11.2 km/s", "同步衛星週期 24 小時", "軌道速率隨半徑減小"] },
        { id: "angular-momentum", title: "角動量守恆", interactive: I,
          concept: "無外力矩時系統角動量保持不變，解釋行星等面積律與溜冰收手加速。改變半徑觀察轉速的補償變化。",
          formula: R`\( L = mvr = I\omega = \text{定值} \)`,
          points: ["等面積律的本質", "半徑縮小則轉速增快", "花式溜冰收手加速", "無外力矩才守恆"] },
        { id: "rotation", title: "剛體轉動與轉動慣量", interactive: I,
          concept: "剛體受力矩作用產生角加速度，是 F=ma 的轉動版本；轉動慣量 I 是轉動的「慣性」，質量分布離軸越遠 I 越大、越難轉動。調整力矩與轉動慣量觀察角加速度。",
          formula: R`\( \tau = I\alpha,\quad I = \sum m_i r_i^2,\quad K = \tfrac{1}{2}I\omega^2 \)`,
          points: ["τ = Iα 為轉動版牛頓第二定律", "轉動慣量是轉動的慣性", "質量離軸越遠越難轉動", "轉動動能 ½Iω²"] },
        { id: "vertical-circle", title: "鉛直圓周運動", interactive: I,
          concept: "繩繫小球（或水桶）在鉛直面內轉動時，速率與繩張力隨高度改變；要通過最高點，最高點速率至少需 √(gr)，否則繩鬆脫、物體脫離圓周。",
          formula: R`\( v_{\text{頂}}^2 \ge gr,\quad T_{\text{底}} = \dfrac{mv^2}{r} + mg,\quad T_{\text{頂}} = \dfrac{mv^2}{r} - mg \)`,
          points: ["最高點最小速率 √(gr)", "最低點張力最大", "最高點靠重力提供部分向心力", "水桶甩水不灑的原理"] }
      ]
    },
    {
      no: "六", id: "shm", title: "簡諧運動", track: "選修力學一", color: "#4fc3f7",
      intro: "彈簧振子與單擺——回復力與位移成正比的週期性運動，位移、速度、加速度與能量的變化。",
      experiments: [
        { id: "spring", title: "彈簧振子", interactive: I,
          concept: "彈簧回復力與位移成正比且方向相反，使物體作簡諧運動；動能與彈性位能週期性互換。調整質量與勁度觀察週期。",
          formula: R`\( F = -kx,\quad T = 2\pi\sqrt{\dfrac{m}{k}},\quad x = A\cos(\omega t) \)`,
          points: ["回復力 F = −kx", "週期與振幅無關", "平衡點速度最大", "端點加速度最大"] },
        { id: "pendulum", title: "單擺", interactive: I,
          concept: "小角度擺動時單擺近似簡諧運動，週期只與擺長和重力有關，與質量、振幅無關。調整擺長觀察週期並可測 g。",
          formula: R`\( T = 2\pi\sqrt{\dfrac{L}{g}},\quad \theta = \theta_0\cos(\omega t) \)`,
          points: ["需小角度近似（< 10°）", "週期與擺錘質量無關", "擺長越長週期越長", "可用來測量 g"] },
        { id: "shm-graph", title: "簡諧運動的位移–時間關係", interactive: I,
          concept: "位移隨時間呈正弦變化，速度與加速度亦為正弦函數且彼此有相位差。調整振幅、週期與相位觀察三條曲線。",
          formula: R`\( x = A\cos(\omega t + \varphi),\ v = -A\omega\sin(\omega t),\ a = -\omega^2 x \)`,
          points: ["ω = 2π/T 為角頻率", "x–t 圖的斜率代表速度", "由圖讀出振幅與週期", "初相位決定 t = 0 的位置"] },
        { id: "shm-phase", title: "簡諧運動的相位關係", interactive: I,
          concept: "位移、速度、加速度同頻率但相位不同；同時觀看三條曲線與旋轉相量。",
          formula: R`\( x=A\cos\omega t,\ v=-\omega A\sin\omega t,\ a=-\omega^2x \)`,
          points: ["速度超前位移 90°", "加速度與位移反相", "平衡點速度最大", "端點加速度最大"] },
        { id: "shm-energy", title: "簡諧運動的能量", interactive: I,
          concept: "簡諧運動中總力學能守恆，動能與位能隨位置交替變化。觀察動能與位能沿位移的分配與總和恆定。",
          formula: R`\( E = \tfrac{1}{2}kA^2,\quad K = \tfrac{1}{2}k(A^2 - x^2) \)`,
          points: ["總能與振幅平方成正比", "平衡點動能最大", "端點位能最大", "能量在動能位能間流動"] },
        { id: "damped-oscillation", title: "阻尼振動", interactive: I,
          concept: "摩擦或阻力會使振幅逐漸衰減；調整阻尼比較欠阻尼、臨界阻尼與過阻尼。",
          formula: R`\( A(t)=A_0e^{-\beta t} \)`,
          points: ["阻尼消耗機械能", "振幅隨時間衰減", "臨界阻尼最快回到平衡", "避震器的原理"] },
        { id: "resonance", title: "共振", interactive: I,
          concept: "外力頻率接近系統自然頻率時，振幅急遽增大。掃動驅動頻率，觀察振幅在共振點附近的尖峰與阻尼影響。",
          formula: R`\( f_{\text{驅動}} \approx f_0,\quad A_{max}\propto \dfrac{1}{\text{阻尼}} \)`,
          points: ["能量最有效傳遞", "橋樑共振破壞", "樂器與收音機選台", "阻尼越小尖峰越高"] }
      ]
    },
    {
      no: "七", id: "thermal", title: "流體與熱學", track: "選修力學二與熱學", color: "#e57373",
      intro: "浮力與白努利原理、理想氣體與分子動能論、氣體定律，以及熱力學基本定律。",
      experiments: [
        { id: "buoyancy", title: "浮力與阿基米德原理", interactive: I,
          concept: "浸在流體中的物體受向上浮力，大小等於排開流體的重量；物體密度小於流體則浮起。調整密度觀察沉浮與沒入比例。",
          formula: R`\( F_b = \rho_{\text{流}}\,g\,V_{\text{排}},\quad \dfrac{V_{\text{沒}}}{V} = \dfrac{\rho_{\text{物}}}{\rho_{\text{流}}} \)`,
          points: ["浮力等於排開流體重量", "沉浮取決於密度比較", "沒入比例 = 密度比", "潛水艇與熱氣球原理"] },
        { id: "spring-scale-buoyancy", title: "彈簧秤量浮力", interactive: I,
          concept: "將物體懸掛於彈簧秤並逐漸浸入水中，彈簧秤示數因浮力而變小。以空氣中與液體中的示數差，可直接量得浮力。",
          formula: R`\( F_b = W - T = \rho_{\text{液}}gV_{\text{排}} \)`,
          points: ["彈簧秤示數為繩張力", "示數差就是浮力", "完全浸沒後浮力不再增加", "可反推排開液體的體積"] },
        { id: "bernoulli", title: "白努利原理", interactive: I,
          concept: "理想流體流速快處壓力小，源自能量守恆。改變管徑，觀察流速與壓力此消彼長，並示範機翼升力。",
          formula: R`\( P + \tfrac{1}{2}\rho v^2 + \rho gh = \text{定值} \)`,
          points: ["流速快壓力低", "連續方程 A₁v₁ = A₂v₂", "機翼升力來源", "文氏管與噴霧器"] },
        { id: "gas", title: "理想氣體與分子動能論", interactive: I,
          concept: "氣體由大量隨機運動的分子組成；溫度反映分子平均動能，分子撞擊器壁形成壓力。調整溫度與體積觀察分子運動與壓力。",
          formula: R`\( PV = nRT,\quad \tfrac{1}{2}m\langle v^2\rangle = \tfrac{3}{2}kT \)`,
          points: ["溫度越高分子平均速率越大", "壓力來自分子碰撞", "PV = nRT 理想氣體方程", "體積縮小壓力增大"] },
        { id: "gas-laws", title: "氣體定律（波以耳/查理）", interactive: I,
          concept: "理想氣體壓力、體積、溫度互相牽動：定溫時 PV 定值，定壓時 V∝T。切換過程，觀察 P–V 圖上的變化。",
          formula: R`\( P_1V_1 = P_2V_2,\quad \dfrac{V_1}{T_1} = \dfrac{V_2}{T_2},\quad \dfrac{P_1}{T_1}=\dfrac{P_2}{T_2} \)`,
          points: ["波以耳定律 PV 定值", "查理定律 V∝T", "給呂薩克 P∝T", "P–V 圖描述熱力過程"] },
        { id: "heat", title: "熱平衡與比熱", interactive: I,
          concept: "兩物體接觸時熱由高溫流向低溫直到達成熱平衡；比熱越大溫度變化越慢。混合冷熱水，觀察終溫由熱量守恆決定。",
          formula: R`\( Q = mc\Delta T,\quad m_1c_1\Delta T_1 = m_2c_2\Delta T_2 \)`,
          points: ["熱量由高溫流向低溫", "比熱是升溫難易的量度", "熱平衡時溫度相同", "熱量守恆（無散失）"] },
        { id: "thermo1", title: "熱力學第一定律", interactive: I,
          concept: "系統內能變化等於吸收的熱量減去對外所做的功，是能量守恆的表現。切換等溫、等壓、絕熱過程觀察能量帳。",
          formula: R`\( \Delta U = Q - W,\quad W = \int P\,dV \)`,
          points: ["內能為狀態函數", "熱與功皆為能量傳遞", "等溫、絕熱等過程分析", "絕熱過程 Q = 0"] }
      ]
    },
    {
      no: "八", id: "waves", title: "波動與聲音", track: "必修 · 選修波動光學", color: "#7986cb",
      intro: "橫波與縱波的性質、波的疊加與干涉、駐波、都卜勒效應、拍與聲音的共鳴。",
      experiments: [
        { id: "wave-types", title: "橫波與縱波", interactive: I,
          concept: "介質振動方向與波前進方向垂直者為橫波、平行者為縱波。調整頻率與振幅，觀察質點振動與波形前進的關係。",
          formula: R`\( v = f\lambda,\quad T = \dfrac{1}{f} \)`,
          points: ["繩波為橫波", "聲波為縱波", "波速由介質決定", "質點振動 vs 波形移動"] },
        { id: "superposition", title: "波的疊加與干涉", interactive: I,
          concept: "兩波相遇時位移相加；相位相同則相長、相反則相消。調整兩波相位差，觀察合成波的相長與相消。",
          formula: R`\( \text{相長：}\Delta = n\lambda,\quad \text{相消：}\Delta = (n+\tfrac{1}{2})\lambda \)`,
          points: ["重疊原理", "相長與相消干涉", "路徑差決定干涉結果", "水波槽實驗"] },
        { id: "standing-wave", title: "弦上的駐波", interactive: I,
          concept: "兩列同頻率、反向前進的波疊加形成駐波；弦上只能存在特定的共振頻率（諧波）。切換諧波階數觀察波節與波腹。",
          formula: R`\( L = n\dfrac{\lambda}{2},\quad f_n = \dfrac{nv}{2L},\quad n = 1,2,3\ldots \)`,
          points: ["波節不動波腹振幅最大", "只有特定頻率能共振", "n = 1 為基頻", "頻率為基頻整數倍"] },
        { id: "doppler", title: "都卜勒效應", interactive: I,
          concept: "波源與觀察者相對運動時，觀察到的頻率改變；接近時變高、遠離時變低。移動波源，觀察前後波長被壓縮與拉長。",
          formula: R`\( f' = f\,\dfrac{v \pm v_o}{v \mp v_s} \)`,
          points: ["接近時頻率升高", "遠離時頻率降低", "波源前方波長被壓縮", "測速與天文紅移"] },
        { id: "beats", title: "拍", interactive: I,
          concept: "兩個頻率相近的波疊加時，合成振幅週期性強弱變化形成拍；拍頻等於兩頻率之差。調整兩頻率觀察拍的快慢。",
          formula: R`\( f_{\text{拍}} = |f_1 - f_2| \)`,
          points: ["頻率相近才聽得到拍", "拍頻 = 頻率差", "調音的原理", "振幅週期性起伏"] },
        { id: "resonance-tube", title: "聲音的共鳴（共鳴管）", interactive: I,
          concept: "空氣柱在特定長度時與音叉產生共鳴，可測聲速。調整管長，觀察開管與閉管的共鳴位置與諧波差異。",
          formula: R`\( \text{開管 } f_n = \dfrac{nv}{2L},\quad \text{閉管 } f_n = \dfrac{(2n-1)v}{4L} \)`,
          points: ["共鳴時振幅最大", "開管含全部諧波", "閉管只含奇次諧波", "可用來測聲速"] }
      ]
    },
    {
      no: "九", id: "optics", title: "光學", track: "必修 · 選修波動光學", color: "#f06292",
      intro: "光的反射與折射、面鏡與透鏡成像，以及干涉、繞射、偏振與色散等波動性質。",
      experiments: [
        { id: "snell", title: "反射與折射（司乃耳定律）", interactive: I,
          concept: "光由一介質進入另一介質時偏折，入射角與折射角遵循司乃耳定律；由密到疏超過臨界角則全反射。拖動入射角觀察。",
          formula: R`\( n_1\sin\theta_1 = n_2\sin\theta_2,\quad \theta_c = \sin^{-1}\!\dfrac{n_2}{n_1} \)`,
          points: ["反射角等於入射角", "折射率決定偏折量", "由疏入密偏向法線", "全反射與臨界角"] },
        { id: "mirror", title: "面鏡成像", interactive: I,
          concept: "凹面鏡與凸面鏡依物距形成不同性質的像；用主要光線作圖找像。移動物體，觀察像的正立/倒立、放大/縮小、虛/實。",
          formula: R`\( \dfrac{1}{f} = \dfrac{1}{p} + \dfrac{1}{q},\quad m = -\dfrac{q}{p},\quad f = \dfrac{R}{2} \)`,
          points: ["凹面鏡可成實像或虛像", "凸面鏡恆成縮小虛像", "焦距 f = R/2", "主要光線作圖法"] },
        { id: "lens", title: "透鏡成像", interactive: I,
          concept: "凸透鏡與凹透鏡依物距形成不同的像；用三條主要光線作圖找像。移動物體，觀察成像規律與應用。",
          formula: R`\( \dfrac{1}{f} = \dfrac{1}{p} + \dfrac{1}{q},\quad m = -\dfrac{q}{p} \)`,
          points: ["凸透鏡會聚光線", "凹透鏡發散光線", "物在 2f 外成縮小倒立實像", "近視與遠視矯正"] },
        { id: "lens-displacement", title: "凸透鏡位移法量焦距", interactive: I,
          concept: "固定物體與光屏的距離，移動凸透鏡可找到兩個都能在光屏成清晰像的位置。量得兩位置間距後，即可由位移法求出焦距。",
          formula: R`\( f = \dfrac{D^2-d^2}{4D},\quad D > 4f \)`,
          points: ["物屏距必須大於 4f", "有兩個清晰像位置", "兩位置距離為 d", "由 D、d 可求焦距"] },
        { id: "double-slit", title: "雙縫干涉", interactive: I,
          concept: "同調光通過雙狹縫後在光屏上形成明暗相間的干涉條紋，證明光具有波動性。調整縫距與波長觀察條紋間距。",
          formula: R`\( d\sin\theta = m\lambda,\quad \Delta y = \dfrac{\lambda L}{d} \)`,
          points: ["亮紋：路程差為 λ 整數倍", "縫距越小條紋越寬", "波長越長條紋越寬", "楊氏實驗證明波動性"] },
        { id: "diffraction", title: "單狹縫繞射", interactive: I,
          concept: "光通過單狹縫會繞射展開，形成中央最寬最亮、兩側逐漸變暗的繞射圖樣。調整縫寬與波長觀察中央亮紋寬度。",
          formula: R`\( a\sin\theta = m\lambda\ (m=1,2,\ldots\text{為暗紋}) \)`,
          points: ["繞射使光偏離直線", "中央亮紋最寬最亮", "縫越窄繞射越明顯", "解析度的極限"] },
        { id: "polarization", title: "偏振", interactive: I,
          concept: "偏振顯示光為橫波；自然光通過偏振片後只剩單一振動方向，再通過第二片時強度依馬呂士定律變化。旋轉偏振片觀察。",
          formula: R`\( I = I_0\cos^2\theta \)`,
          points: ["偏振證明光為橫波", "馬呂士定律 I = I₀cos²θ", "兩片垂直時全暗", "偏光太陽眼鏡應用"] },
        { id: "dispersion", title: "色散與稜鏡", interactive: I,
          concept: "介質折射率隨波長不同，使白光經稜鏡分解成彩色光譜；紫光偏折最多、紅光最少。調整入射角觀察分光。",
          formula: R`\( n_{\text{紫}} > n_{\text{紅}} \;\Rightarrow\; \theta_{\text{紫}} > \theta_{\text{紅}} \)`,
          points: ["折射率隨波長改變", "紫光偏折最多", "白光分解為光譜", "彩虹的成因"] },
        { id: "grating", title: "繞射光柵", interactive: I,
          concept: "光柵有極多等距狹縫，各縫光干涉後只在特定角度形成又亮又細的主極大，且不同波長分開角度不同，因此能把光精確分解成光譜。縫距越小、級數越高分得越開。",
          formula: R`\( d\sin\theta = m\lambda,\quad m = 0, \pm1, \pm2, \ldots \)`,
          points: ["主極大又亮又銳利", "縫距 d 越小譜線分得越開", "同一角度不同波長即分光", "級數 m 越高偏折越大"] }
      ]
    },
    {
      no: "十", id: "electric", title: "電場與電路", track: "必修 · 選修電磁學", color: "#4db6ac",
      intro: "庫侖定律、電場與電位、電容器，以及歐姆定律、閉合電路、電阻串並聯與電路分析。",
      experiments: [
        { id: "coulomb", title: "庫侖定律", interactive: I,
          concept: "兩點電荷間的靜電力與電量乘積成正比、與距離平方成反比，同性相斥、異性相吸。調整電量與距離觀察靜電力。",
          formula: R`\( F = k\dfrac{q_1 q_2}{r^2},\quad k = 9\times10^{9}\ \mathrm{N\,m^2/C^2} \)`,
          points: ["同性相斥異性相吸", "平方反比定律", "與萬有引力形式相同", "距離加倍力變 1/4"] },
        { id: "efield", title: "電場線與等勢面", interactive: I,
          concept: "電荷在周圍空間產生電場，以電場線表示方向與強弱；與電場線垂直者為等勢面。拖動電荷觀察電場線與等勢面。",
          formula: R`\( E = \dfrac{kQ}{r^2},\quad V = \dfrac{kQ}{r} \)`,
          points: ["電場線由正電荷指向負電荷", "電場線密處場強大", "等勢面與電場線垂直", "沿等勢面移動不做功"] },
        { id: "potential-e", title: "電位與電位能", interactive: I,
          concept: "單位電荷在電場中所具有的位能為電位（純量）。在均勻電場中移動試驗電荷，觀察電位差、電場與作功的關係。",
          formula: R`\( V = \dfrac{U}{q},\quad E = \dfrac{V}{d},\quad W = q\,\Delta V \)`,
          points: ["電位差驅動電流", "沿電場方向電位下降", "等勢面電位相同", "單位為伏特"] },
        { id: "ohms", title: "歐姆定律與電路", interactive: I,
          concept: "導體兩端電壓與電流成正比，比值為電阻。調整電壓與電阻，觀察電流與功率如何變化。",
          formula: R`\( V = IR,\quad P = IV = I^2R = \dfrac{V^2}{R} \)`,
          points: ["電阻阻礙電流", "V 與 I 成正比", "功率 P = IV", "電阻發熱效應"] },
        { id: "iv-measurement", title: "伏安法量電阻與 U-I 作圖", interactive: I,
          concept: "安培計必須串聯、電壓計必須並聯在被測電阻兩端。改變可變電阻並記錄 U、I，從 U-I 圖斜率求得被測電阻。",
          formula: R`\( U = IR,\quad R = \dfrac{\Delta U}{\Delta I} \)`,
          points: ["安培計串聯、電壓計並聯", "先選擇合適量程", "U-I 圖斜率即電阻", "至少量測多組資料再判讀"] },
        { id: "closed-circuit-emf", title: "閉合電路：電動勢與內電阻量測", interactive: I,
          concept: "真實電源可視為理想電動勢 E 串聯內阻 r。改變外電阻並記錄路端電壓與電流，從量測圖線的截距和斜率反推出電動勢與內阻。",
          formula: R`\( E = U + Ir,\quad U = E - Ir,\quad I = \dfrac{E}{R+r} \)`,
          points: ["路端電壓隨電流增加而下降", "U-I 圖截距為 E、斜率為 -r", "短路電流 I_s = E/r", "負載功率最大時 R = r"] },
        { id: "resistors", title: "電阻的串聯與並聯", interactive: I,
          concept: "串聯電阻相加、電流相同；並聯電阻倒數相加、電壓相同。切換接法，觀察等效電阻、分壓與分流。",
          formula: R`\( R_s = \sum R_i,\quad \dfrac{1}{R_p} = \sum \dfrac{1}{R_i} \)`,
          points: ["串聯分壓電流相同", "並聯分流電壓相同", "並聯總電阻比任一支路小", "電流走捷徑（低阻）"] },
        { id: "capacitor", title: "電容器充放電", interactive: I,
          concept: "電容器透過電阻充放電時，電壓與電流呈指數變化，時間常數 τ = RC 決定快慢。切換充放電觀察指數曲線。",
          formula: R`\( C = \dfrac{Q}{V},\quad \tau = RC,\quad V = V_0(1-e^{-t/\tau}) \)`,
          points: ["電容器儲存電荷與電能", "時間常數 τ = RC", "充電電壓指數上升", "放電電流指數衰減"] },
        { id: "wheatstone", title: "惠斯登電橋", interactive: I,
          concept: "四個電阻構成橋式電路，中間接檢流計。當對邊電阻乘積相等（R₁Rx = R₂R₃）時橋達平衡、檢流計無電流，可由三個已知電阻精確求出未知電阻。",
          formula: R`\( \dfrac{R_1}{R_2} = \dfrac{R_3}{R_x}\ \Rightarrow\ R_x = \dfrac{R_2 R_3}{R_1} \)`,
          points: ["平衡時檢流計電流為零", "平衡條件：對邊乘積相等", "與電源電壓無關", "可精密量測未知電阻"] },
        { id: "e-deflection", title: "帶電粒子在電場中的偏轉", interactive: I,
          concept: "帶電粒子水平射入平行板間的均勻電場，水平方向等速、鉛直方向受電力等加速，軌跡為拋物線——與拋體運動完全類比，是陰極射線管與示波器的原理。",
          formula: R`\( a = \dfrac{qE}{m},\quad y = \dfrac{qE}{2m}\left(\dfrac{L}{v}\right)^2 \)`,
          points: ["水平等速、鉛直等加速", "軌跡為拋物線（類比拋體）", "偏轉量與電場成正比、與 v² 成反比", "示波器與映像管原理"] },
        { id: "potential-terrain", title: "電勢地形：把電位看成山丘", interactive: I,
          concept: "電位是看不見的純量場。把兩顆可拖曳電荷的電位直接長成地形：正電荷是紅色山丘、負電荷是藍色漏斗，地形越陡處電場越強；電場線永遠垂直穿過等勢面。拖曳電荷、放置探測點，電位的空間感一眼建立。",
          formula: R`\( V = \sum \dfrac{kq_i}{r_i},\quad E = -\dfrac{dV}{dr} \)`,
          points: ["正電荷是山丘、負電荷是漏斗", "地形越陡＝電場越強", "沿著等高線走電位不變", "電場指向下坡方向"] },
        { id: "circuit-sandbox", title: "電路工坊：自由接線實驗室", interactive: I,
          concept: "桌上擺著電池組、閘刀開關、小燈泡、滑動變阻器與兩顆電表——點擊接線柱把它們自由接起來，電路即時求解：燈泡真的會亮、電表真的會動，把電池兩極直接接起來還會短路。切到電路圖模式，課本符號就長在器材的位置上。",
          formula: R`\( \varepsilon = I(r+R),\quad P = I^2R,\quad \text{MNA 節點電壓法即時求解} \)`,
          points: ["安培計串聯、伏特計並聯", "短路時電流只受內阻限制", "串聯分壓、並聯分流自由比較", "實物圖與電路圖一一對應"] }
      ]
    },
    {
      no: "十一", id: "magnetism", title: "磁場與電磁感應", track: "必修 · 選修電磁學", color: "#9575cd",
      intro: "載流導線的磁場、勞侖茲力、法拉第電磁感應與楞次定律，以及交流發電機與變壓器。",
      experiments: [
        { id: "current-field", title: "載流導線的磁場", interactive: I,
          concept: "電流在周圍產生磁場，方向由安培右手定則決定，直線導線的磁場與距離成反比。調整電流觀察磁場方向與強弱。",
          formula: R`\( \text{直線 } B = \dfrac{\mu_0 I}{2\pi r},\quad \text{螺線管 } B = \mu_0 n I \)`,
          points: ["電流磁效應", "安培右手定則", "磁場繞導線成圓", "電磁鐵原理"] },
        { id: "lorentz", title: "磁場與勞侖茲力", interactive: I,
          concept: "運動電荷在磁場中受力，方向由右手定則決定；力恆垂直速度，使帶電粒子作等速率圓周運動。調整速度與磁場觀察半徑。",
          formula: R`\( F = qvB\sin\theta,\quad r = \dfrac{mv}{qB},\quad T = \dfrac{2\pi m}{qB} \)`,
          points: ["力垂直速度與磁場", "帶電粒子作圓周運動", "半徑與動量成正比", "週期與速率無關"] },
        { id: "induction", title: "電磁感應（法拉第定律）", interactive: I,
          concept: "磁通量改變會在線圈感應出電動勢；變化越快電動勢越大。移動磁鐵穿過線圈，觀察感應電流的產生與方向。",
          formula: R`\( \varepsilon = -N\dfrac{\Delta\Phi}{\Delta t},\quad \Phi = BA\cos\theta \)`,
          points: ["磁通量變化才有感應電流", "變化越快電動勢越大", "楞次定律定方向", "發電機的基本原理"] },
        { id: "lenz", title: "楞次定律", interactive: I,
          concept: "感應電流的磁場總是反抗原磁通量的變化，體現能量守恆。觀察磁鐵接近與遠離時感應電流方向如何反抗運動。",
          formula: R`\( \varepsilon = -N\dfrac{d\Phi}{dt} \)`,
          points: ["反抗磁通變化", "能量守恆的展現", "電磁煞車應用", "感應電流方向的判準"] },
        { id: "ac-generator", title: "交流發電機", interactive: I,
          concept: "線圈在均勻磁場中轉動，使磁通量週期變化，感應出正弦式交流電動勢。調整轉速，觀察感應電動勢的波形。",
          formula: R`\( \varepsilon = \varepsilon_0\sin(\omega t),\quad \varepsilon_0 = NBA\omega \)`,
          points: ["旋轉線圈產生交流電", "電動勢隨轉速增大", "磁通與電動勢相位差 90°", "發電廠的核心"] },
        { id: "transformer", title: "變壓器", interactive: I,
          concept: "利用電磁感應改變交流電壓，電壓比等於匝數比；理想變壓器功率守恆。調整匝數比，觀察升壓/降壓與電流的反向變化。",
          formula: R`\( \dfrac{V_s}{V_p} = \dfrac{N_s}{N_p},\quad V_pI_p = V_sI_s \)`,
          points: ["電壓比 = 匝數比", "升壓則降流", "理想變壓器功率守恆", "高壓輸電降低損耗"] },
        { id: "em-wave", title: "電磁波與電磁波譜", interactive: I,
          concept: "變化的電場與磁場互相激發，形成在空間中傳播的電磁波；電場、磁場互相垂直，也垂直於前進方向。所有電磁波在真空中皆以光速前進。調整波長觀察它落在電磁波譜的哪個波段。",
          formula: R`\( c = f\lambda = 3\times10^{8}\ \mathrm{m/s} \)`,
          points: ["電場與磁場互相垂直", "橫波、不需介質", "真空中皆以光速前進", "波譜：無線電→微波→紅外→可見→紫外→X→γ"] },
        { id: "mass-spec", title: "質譜儀（速度選擇器）", interactive: I,
          concept: "先用互相垂直的電場與磁場組成速度選擇器，只有 v = E/B 的離子能直線通過；接著進入磁場區作圓周運動，半徑正比於質量，於是不同質量的離子分開落點，可測質量。",
          formula: R`\( v = \dfrac{E}{B},\quad r = \dfrac{mv}{qB'} \)`,
          points: ["速度選擇器：電力與磁力平衡", "只有特定速率能直線通過", "偏轉半徑正比於質量", "依落點分離不同質量離子"] }
      ]
    },
    {
      no: "十二", id: "modern", title: "近代物理與宇宙學", track: "必修 · 選修近代物理", color: "#ffb74d",
      intro: "光電效應、原子模型、物質波、狹義相對論、原子核與放射性，以及大霹靂與宇宙膨脹。",
      experiments: [
        { id: "photoelectric", title: "光電效應", interactive: I,
          concept: "光照射金屬時若頻率足夠高即射出電子；光以光子形式攜帶能量，證明光的粒子性。調整頻率與光強觀察光電子。",
          formula: R`\( E = hf,\quad hf = W + K_{max},\quad K_{max} = hf - W \)`,
          points: ["需超過底限頻率才有電子", "增加光強只增加電子數", "光子能量與頻率成正比", "愛因斯坦以此獲諾貝爾獎"] },
        { id: "bohr", title: "波耳原子模型與原子光譜", interactive: I,
          concept: "電子只能在特定能階運行，躍遷時吸收或放出特定頻率的光，形成不連續的原子光譜。切換能階觀察躍遷與譜線。",
          formula: R`\( E_n = -\dfrac{13.6}{n^2}\ \mathrm{eV},\quad \Delta E = hf = \dfrac{1240}{\lambda[\mathrm{nm}]} \)`,
          points: ["能階量子化", "躍遷放出特定波長的光", "萊曼系（紫外）、巴耳末系（可見）", "解釋氫原子光譜"] },
        { id: "matter-wave", title: "物質波（德布羅意）", interactive: I,
          concept: "運動的粒子也具有波動性，波長與動量成反比。調整粒子速度與質量，觀察物質波波長與電子繞射。",
          formula: R`\( \lambda = \dfrac{h}{p} = \dfrac{h}{mv} \)`,
          points: ["波粒二象性", "電子繞射實驗證實", "速度越大波長越短", "電子顯微鏡原理"] },
        { id: "relativity", title: "狹義相對論", interactive: I,
          concept: "接近光速時時間膨脹、長度收縮；用光鐘可看出運動時鐘走得較慢。調整速度觀察時間膨脹因子 γ 的變化。",
          formula: R`\( \gamma = \dfrac{1}{\sqrt{1 - v^2/c^2}},\quad t = \gamma t_0,\quad E = mc^2 \)`,
          points: ["光速為恆定上限", "時間膨脹與長度收縮", "質能等價 E = mc²", "v→c 時 γ→∞"] },
        { id: "halflife", title: "原子核與放射性半衰期", interactive: I,
          concept: "不穩定原子核放出 α、β、γ 射線而衰變，每經一個半衰期數量減半。調整半衰期，觀察衰變曲線與剩餘核數。",
          formula: R`\( N = N_0\left(\tfrac{1}{2}\right)^{t/T_{1/2}} \)`,
          points: ["三種放射線性質不同", "半衰期為統計特性", "每半衰期數量減半", "碳-14 定年法"] },
        { id: "hubble", title: "大霹靂與哈伯定律", interactive: I,
          concept: "從多個星系的距離與譜線紅移取得退行速度，繪成 v–d 散點圖；通過資料趨勢的最佳擬合線斜率就是哈伯常數 H₀。",
          formula: R`\( v = H_0 d,\quad z\approx\frac{v}{c} \)`,
          points: ["每一個散點代表一個星系的距離與退行速度", "最佳擬合線斜率就是哈伯常數 H₀", "距離較遠的星系通常有較大的紅移", "單筆資料有雜訊，需用多筆觀測看趨勢"] },
        { id: "millikan", title: "密立根油滴實驗", interactive: I,
          concept: "帶電油滴懸浮在平行板電場中，向上電力與向下重力平衡時油滴靜止。調整電壓使油滴懸浮即可求電量，且測得電量都是基本電荷 e 的整數倍——證明電荷量子化。",
          formula: R`\( qE = mg,\quad q = \dfrac{mgd}{V},\quad q = n e \)`,
          points: ["電力與重力平衡則懸浮", "電量為基本電荷的整數倍", "e ≈ 1.6×10⁻¹⁹ C", "證明電荷是量子化的"] },
        { id: "rutherford", title: "拉塞福散射（金箔實驗）", interactive: I,
          concept: "以 α 粒子撞擊金箔，多數幾乎直線穿過，少數卻大角度偏折甚至反彈。這說明原子的正電荷與絕大部分質量集中在極小的原子核上，推翻了均勻分布的模型。",
          formula: R`\( F = \dfrac{k(2e)(Ze)}{r^2} \)`,
          points: ["多數 α 粒子直線穿過", "少數大角度偏折", "原子核又小又重、帶正電", "原子內部幾乎是空的"] }
      ]
    }
  ];

  // 第二批課程地圖：把課本中常被併入章節段落的關鍵知識點拆成獨立操作實驗。
  const EXTENDED_EXPERIMENTS = {
    kinematics: [
      { id: "vector-components", title: "位移與速度的向量分解", interactive: I, concept: "將斜向位移或速度分解為互相垂直的分量；改變大小與方向，觀察分量如何決定合向量。", formula: R`\( A_x=A\cos\theta,\quad A_y=A\sin\theta \)`, points: ["向量有大小與方向", "正交分量可獨立處理", "合量由畢氏定理求得", "拋體運動可分方向分析"] },
      { id: "distance-displacement", title: "路程、位移與平均速度", interactive: I, concept: "沿直線先走到折返點再往回走；路程把去程與回程的長度相加，位移只比較終點相對起點的位置與方向。", formula: R`\( s=L+rL,\quad \Delta x=x_{\text{終}}-x_{\text{起}} \)`, points: ["路程為實際走過的總長，永遠不為負", "位移是起點指向終點的有向量", "回到原點時位移為零，但路程不為零", "平均速度與平均速率分別使用位移與路程"] },
      { id: "measurement-error", title: "量測、不確定度與有效數字", interactive: I, concept: "用同一把尺反覆量測固定長度；每筆讀值會因讀取雜訊、儀器解析度與零點偏移略有不同，從讀值分布建立平均值與不確定度。", formula: R`\( \bar x=\frac{1}{n}\sum x_i,\quad u(\bar x)\sim\frac{s}{\sqrt n} \)`, points: ["每一個點是一筆獨立讀值，散開不等於做錯", "解析度決定讀值可分辨到多細", "重複量測讓平均值更穩定，但不會消除系統誤差", "結果可寫成平均值 ± 不確定度，並附單位"] }
    ],
    newton: [
      { id: "force-components", title: "力的分解與正交合成", interactive: I, concept: "把一個斜向拉力分解為水平與鉛直分量，觀察角度改變如何影響物體的受力平衡。", formula: R`\( F_x=F\cos\theta,\quad F_y=F\sin\theta \)`, points: ["先選座標軸", "分量可分別列方程", "合力由分量相加", "常用於斜面與拉繩題"] },
      { id: "apparent-weight", title: "超重與失重（電梯）", interactive: I, concept: "電梯加速時體重計讀數為支持力 N=m(g+a)，不是固定的 mg。", formula: R`\( N=m(g+a) \)`, points: ["向上加速會超重", "向下加速會失重", "自由落體時 N=0", "重量 mg 不隨運動改變"] },
      { id: "spring-series-parallel", title: "彈簧串聯與並聯", interactive: I, concept: "兩彈簧串聯會變軟、並聯會變硬；以等效勁度比較相同外力下的伸長。", formula: R`\( \frac{1}{k_s}=\frac{1}{k_1}+\frac{1}{k_2},\quad k_p=k_1+k_2 \)`, points: ["串聯伸長量相加", "並聯受力分攤", "等效勁度決定變形", "符合虎克定律"] }
    ],
    momentum: [
      { id: "center-of-mass", title: "質心與系統運動", interactive: I, concept: "系統內部物體可互相移動，但在外力為零時質心依然做等速直線運動。", formula: R`\( x_{cm}=\frac{\sum m_ix_i}{\sum m_i} \)`, points: ["質心是質量加權平均位置", "內力不改變質心運動", "爆炸後質心軌跡連續", "適用多物體系統"] },
      { id: "force-time-profile", title: "力—時間曲線與緩衝", interactive: I, concept: "選擇不同碰撞力的時間分布，比較曲線面積相同時峰值力如何隨作用時間改變。", formula: R`\( J=\int Fdt=\Delta p \)`, points: ["曲線面積是衝量", "時間拉長可降峰值力", "安全氣囊增加作用時間", "平均力由面積除時間"] },
      { id: "rocket-equation", title: "火箭推進與質量流失", interactive: I, concept: "火箭向後噴出燃氣而向前加速；觀察噴氣速度與燃料消耗如何影響推進結果。", formula: R`\( \Delta v=v_e\ln\frac{m_0}{m_f} \)`, points: ["反衝來自動量守恆", "不需要空氣也能推進", "排氣速度越大增速越大", "燃料使初始質量變大"] }
    ],
    energy: [
      { id: "work-angle", title: "功與力的夾角", interactive: I, concept: "只有沿位移方向的力分量做功；拖動力的方向，觀察正功、零功與負功。", formula: R`\( W=Fs\cos\theta \)`, points: ["平行位移做功最大", "垂直位移不做功", "反向力做負功", "功是能量轉移"] },
      { id: "power-lab", title: "功率與效率", interactive: I, concept: "在相同做功下，完成時間越短，功率越大；加入損耗後可比較輸入與有用輸出。", formula: R`\( P=\frac{W}{t}=Fv,\quad \eta=\frac{P_{out}}{P_{in}} \)`, points: ["功率描述做功快慢", "同功不同時間功率不同", "效率小於等於 1", "常見於馬達與爬樓梯"] },
      { id: "friction-thermal", title: "摩擦耗散與熱能", interactive: I, concept: "滑塊受摩擦後，機械能減少並轉為內能；調整摩擦係數比較停止距離與熱量。", formula: R`\( W_f=-f_kd,\quad Q=f_kd \)`, points: ["非保守力改變機械能", "摩擦做負功", "損失的機械能轉為內能", "能量仍守恆"] }
    ],
    gravity: [
      { id: "banked-curve", title: "傾斜彎道與向心力", interactive: I, concept: "車在傾斜彎道上可由正向力的水平分量提供向心力；改變速度與傾角判讀是否打滑。", formula: R`\( \tan\theta=\frac{v^2}{rg} \)`, points: ["正向力的水平分量提供向心力", "傾角決定設計速度", "過快或過慢需摩擦補償", "道路與賽車彎道應用"] },
      { id: "satellite-energy", title: "衛星軌道能量", interactive: I, concept: "衛星的重力位能與動能隨半徑改變；圓軌道的總機械能為負值。", formula: R`\( v=\sqrt{GM/r},\quad E=-\frac{GMm}{2r} \)`, points: ["重力提供向心力", "軌道半徑越大速度越小", "束縛系統總能量為負", "地球同步衛星有特定半徑"] },
      { id: "escape-speed", title: "逃逸速度", interactive: I, concept: "從天體表面出發的物體若總能量不小於零，就能脫離重力束縛。", formula: R`\( v_e=\sqrt{\frac{2GM}{R}} \)`, points: ["忽略空氣阻力", "與發射物質量無關", "地表約 11.2 km/s", "並非離開大氣層的速度"] }
    ],
    shm: [
      /* 阻尼振動與相位關係已併入主模組，讓「阻尼」在「共振」之前登場（跳階修正）。 */
      { id: "coupled-oscillators", title: "耦合振子與能量交換", interactive: I, concept: "兩個以彈簧連結的振子會週期性交換能量，形成拍與正常模態。", formula: R`\( E_1+E_2=\text{定值} \)`, points: ["能量在振子間傳遞", "總能量近似守恆", "可見拍的包絡", "正常模態有固定相位"] }
    ],
    thermal: [
      { id: "hydrostatic-pressure", title: "液體壓力與深度", interactive: I, concept: "靜止液體內壓力隨深度線性增加，與容器形狀無關。", formula: R`\( P=P_0+\rho gh \)`, points: ["深度越大壓力越大", "同深度壓力相同", "與容器形狀無關", "水壩底部更厚"] },
      { id: "phase-change", title: "相變與加熱曲線", interactive: I, concept: "物質在熔化、沸騰時吸收熱量但溫度保持不變；切換加熱功率觀察平台。", formula: R`\( Q=mc\Delta T,\quad Q=mL \)`, points: ["相變時溫度不變", "潛熱用來改變狀態", "斜段由比熱決定", "平台長度與質量成正比"] },
      { id: "heat-engine", title: "熱機、效率與熵方向", interactive: I, concept: "熱機從高溫熱源吸熱，部分轉為功，其餘排向低溫熱源；效率受溫度限制。", formula: R`\( \eta=\frac{W}{Q_H}\le1-\frac{T_C}{T_H} \)`, points: ["不可能把熱全轉為功", "需高溫與低溫熱源", "卡諾效率是上限", "熱自發由高溫流向低溫"] }
    ],
    waves: [
      { id: "reflection-boundary", title: "波的反射與邊界", interactive: I, concept: "波遇固定端反射會反相，遇自由端反射不反相；切換邊界條件觀察脈衝回傳。", formula: R`\( y_{\text{反}}=\pm y_{\text{入}} \)`, points: ["固定端反相", "自由端同相", "反射波速不變", "疊加可形成駐波"] },
      { id: "sound-intensity", title: "聲音強度與分貝", interactive: I, concept: "聲強與振幅平方成正比，分貝尺度是對數尺度；調整距離與振幅比較聽覺變化。", formula: R`\( \beta=10\log_{10}(I/I_0) \)`, points: ["分貝是對數單位", "距離增加聲強下降", "振幅影響響度", "頻率影響音調"] },
      { id: "air-column-resonance", title: "共鳴管與空氣柱", interactive: I, concept: "改變空氣柱長度，尋找聲音最響的共鳴位置，並由相鄰共鳴長度求波長。", formula: R`\( L_n=(2n-1)\frac{\lambda}{4} \)`, points: ["一端閉管為四分之一波長", "相鄰共鳴差 λ/2", "頻率由音叉決定", "可量測聲速"] }
    ],
    optics: [
      { id: "critical-angle", title: "全反射與臨界角", interactive: I, concept: "光從高折射率介質射向低折射率介質時，入射角超過臨界角將完全反射。", formula: R`\( \sin\theta_c=\frac{n_2}{n_1} \)`, points: ["需從光密介質射向光疏介質", "臨界角時折射角 90°", "光纖利用全反射", "反射仍遵守反射定律"] },
      { id: "refraction-slab", title: "平行玻璃板的側向位移", interactive: I, concept: "光穿過平行玻璃板後出射光與入射光平行，但會產生可量測的側向位移。", formula: R`\( n_1\sin\theta_1=n_2\sin\theta_2 \)`, points: ["兩次折射方向相反", "出射光與入射光平行", "厚度越大位移越大", "折射率決定偏折量"] },
      { id: "optical-instruments", title: "顯微鏡與望遠鏡", interactive: I, concept: "複合顯微鏡以物鏡形成放大實像，再由目鏡放大；望遠鏡則將遠物成像於焦平面。", formula: R`\( M_{tel}=f_o/f_e \)`, points: ["物鏡負責集光成像", "目鏡負責角放大", "焦距比決定倍率", "像面需對焦"] }
    ],
    electric: [
      { id: "kirchhoff", title: "基爾霍夫電路定律", interactive: I, concept: "在分岔點電流守恆、在閉合迴路電位升降總和為零；調整支路電阻解讀各支路電流。", formula: R`\( \sum I_{in}=\sum I_{out},\quad \sum\Delta V=0 \)`, points: ["電荷守恆給出節點定律", "能量守恆給出迴路定律", "支路電流可不同", "適用複雜電路"] },
      { id: "meter-loading", title: "電表內阻與量測負載效應", interactive: I, concept: "真實電壓表與電流表都有內阻，接入電路會改變原本狀態；調整內阻比較量測誤差。", formula: R`\( R_V\gg R,\quad R_A\ll R \)`, points: ["電壓表應高內阻", "電流表應低內阻", "量測工具會擾動系統", "需注意接法與量程"] },
      { id: "electrostatic-shield", title: "靜電屏蔽與法拉第籠", interactive: I, concept: "導體在靜電平衡時內部電場為零，電荷分布在表面；觀察外部電荷如何被金屬殼屏蔽。", formula: R`\( E_{\text{導體內}}=0 \)`, points: ["自由電荷重新分布", "導體內部等電位", "空腔可屏蔽外電場", "汽車金屬殼是應用"] }
    ],
    magnetism: [
      { id: "ampere-force", title: "安培力的方向與大小", interactive: I, concept: "通電直導線置於磁場中受到安培力；改變電流方向、磁場方向與夾角，觀察受力。", formula: R`\( F=BIL\sin\theta \)`, points: ["力垂直電流與磁場", "夾角 90° 時最大", "反轉電流力反向", "馬達的基礎"] },
      { id: "motional-emf", title: "動生電動勢", interactive: I, concept: "導體棒切割磁力線時，移動電荷受洛倫茲力而兩端產生電位差。", formula: R`\( \varepsilon=BLv \)`, points: ["速度越快電壓越大", "棒長越大電壓越大", "方向可用右手定則", "發電機的局部模型"] },
      { id: "rail-rods", title: "雙棒導軌：電磁剎車與動量傳遞", interactive: I, concept: "兩根導體棒放在光滑的平行導軌上，磁場垂直紙面。棒1以初速滑動時切割磁力線，迴路產生感應電流：棒1被安培力煞車、棒2被推動，直到兩棒同速——動量守恆依然成立，減少的動能變成迴路的焦耳熱。", formula: R`\( \varepsilon=BL(v_1-v_2),\quad F=BIL,\quad m_1v_{10}=(m_1+m_2)v^* \)`, points: ["相對速度才決定感應電動勢", "安培力使快棒減速、慢棒加速", "達共同速度後電流歸零", "動能損失＝迴路焦耳熱"] },
      { id: "coil-torque", title: "通電線圈的力矩", interactive: I, concept: "線圈在磁場中兩側受安培力形成力偶，驅動轉子旋轉；改變角度觀察力矩。", formula: R`\( \tau=NIAB\sin\theta \)`, points: ["平面平行磁場時力矩最大", "法線平行磁場時力矩為零", "直流馬達需要換向", "線圈匝數增加力矩增大"] }
    ],
    modern: [
      { id: "nuclear-reaction", title: "核反應與質能轉換", interactive: I, concept: "核融合與核分裂前後的質量差會轉為巨大能量；比較不同反應的束縛能與能量釋放。", formula: R`\( E=\Delta mc^2 \)`, points: ["質量虧損轉為能量", "融合驅動恆星", "分裂可形成鏈式反應", "核能密度遠高於化學能"] },
      { id: "cosmological-redshift", title: "宇宙紅移與光譜", interactive: I, concept: "遙遠星系遠離時，光波長被宇宙膨脹拉長，譜線向紅端位移。", formula: R`\( z=\frac{\Delta\lambda}{\lambda_0}\approx\frac{v}{c} \)`, points: ["紅移表示遠離", "譜線提供速度資訊", "小紅移可近似都卜勒效應", "支持宇宙膨脹"] },
      { id: "blackbody", title: "黑體輻射與恆星顏色", interactive: I, concept: "黑體光譜峰值隨溫度升高而向短波移動；恆星顏色可反映表面溫度。", formula: R`\( \lambda_{max}T=b \)`, points: ["溫度越高峰值越偏藍", "總輻射功率隨 T^4 增加", "黑體是理想吸收體", "可估計恆星溫度"] }
    ]
  };
  MODULES.forEach(module => { module.experiments.push(...(EXTENDED_EXPERIMENTS[module.id] || [])); });

  let expCount = 0, interactiveCount = 0;
  MODULES.forEach(m => m.experiments.forEach(e => { expCount++; if (e.interactive) interactiveCount++; }));

  window.PhysicsLabCurriculum = {
    modules: MODULES,
    totalModules: MODULES.length,
    totalExperiments: expCount,
    totalInteractive: interactiveCount
  };
})();
